OutSystems/outsystems-datagrid

- azure-pipelines.yml
- jobs/azure-pipelines-reactive.yml
- jobs/azure-pipelines-template.yml
This PR is for improving the tests pipeline
* Whenever there was no sample to test, we would install dependencies and do other unnecessary tasks.
* Changed tasks order. Now we ping sample first, if we get 200 status, we proceed with other tasks. If we get status 404, we skip everything
> RGRIDT-709: Improving tests pipeline

- code/src/Columns/AbstractProviderColumn.ts
- code/src/Features/ValidationMark.ts
- code/src/Features/View.ts
- code/src/Grid/AbstractGrid.ts
- code/src/Grid/FlexGrid.ts
- code/src/Helpers/JSONParser.ts
* Load view isn't working on production
* The column.binding is back to the columns Map
* Created new methods _getColumns(): []_, _hasColumn(key: string)_
* To avoid the usage of grid.columns as an array, the getter was removed, and the methods _hasColumn_, _getColumn_ and _getColumns_ should be used on its place
1. Test the Validations
2. Test the Save/Load View
> Hotfix - SaveLoad Configs

- code/src/Columns/Configuration.ts
- code/src/Features/View.ts
* Width wasn't being reseted when width = undefined
* Visible wasn't being reseted when visible = undefined
* Placing defaults for width and visible, null and true respectively
> HotFix for width and visibility during Save/Load View

- code/src/OSFramework/Grid/AbstractDataSource.ts
- code/src/OSFramework/OSStructure/RowData.ts
- code/src/WijmoProvider/Features/Rows.ts
This PR is based on [RGRIDT-748 - DataSource review](https://github.com/OutSystems/outsystems-datagrid-reactive/pull/74)
* The new item that was being added to the rows with the "Add New Row" action wasn't considering the dataItem column name keys. So, when the row was added, we were not able to edit the cells from the same rows.
* After adding new rows, only the first row had dirty marks.
* The search by server-side was "pushing" new rows to the grid instead of filtering the old ones.
* Get All Selections Data and Get Selected Rows Data from the API were adding the grid to the returning objects
* Added parseNewItem to the addRow method
* Triggered the event of adding the new row to add the dirty marks to new rows
* Fixed the Search mechanism for a value with server side
* Fixed the …
> Corrections to the PR

- .gitignore
- code/src/OSFramework/Feature/IGroupPanel.ts
- code/src/WijmoProvider/Columns/AbstractProviderColumn.ts
- code/src/WijmoProvider/Columns/AbstractProviderColumnEditor.ts
- code/src/WijmoProvider/Features/GroupPanel.ts
This PR is for RGRIDT-792: Fix visiblity behavior after changing properties with columns inside group panel 
* If you move a column to the group panel and then select the same column (on the sample) to change any parameter from optional configs you can see that the same column is appearing on the grid (again) even though it is also being shown in the group panel. The problem seems to come from the method applyConfigs and the isVisible parameter from columns.
* Added more code to make sure the visibility is right when passed into the providerConfigs which are going to get copied into the provider (Wijmo's columns)
BUG:
> RGRIDT-792: Fix visiblity behavior after changing properties with columns inside group panel 

- code/src/OSFramework/Grid/AbstractDataSource.ts
This PR is for RGRIDT-791: Can't edit new added rows on grid with multiple entities.
* When the data from the Grid has additional attributes on the aggregate that later feeds the grid with data and you try to add rows to the grid using the API (GridAPI.AddRows), it's impossible to edit the values of those new cells.
* There was an if statement inside the addRows method (from AbstractDataSource.ts) that was only considering the creation of new dataItems when the grid had a single entity. (e.g. json received -> {"Sample_Product": {Id: 1, Name: "NameValue", Description: "DescriptionValue",  … }). With this fix, that removed that if statement, we should be able to allow the creation of new dataItems for multiple entities (e.g. {"Entity1": {Id: 1, Type: 5}, "Sample_Product": {Id: 1, Name: …
> RGRIDT-791: Removed the validation isSingleEntity from addRows

- code/src/WijmoProvider/Columns/DropdownColumn.ts
This PR is for RGRIDT-792: Fix visiblity behavior after changing properties with columns inside group panel 
* If you move a column to the group panel and then select the same column (on the sample) to change any parameter from optional configs you can see that the same column is appearing on the grid (again) even though it is also being shown in the group panel. The problem seems to come from the method applyConfigs and the isVisible parameter from columns.
* Added more code to make sure the visibility is right when passed into the providerConfigs which are going to get copied into the provider (Wijmo's columns)
BUG:
> Fix Dropdown Columns visibility

- code/src/WijmoProvider/Features/Rows.ts
This PR is for Fixing add rows when changing pages
* There was a bug when you added rows when changing pages
* Adjusted the row index to respect page index as well.
1. Change pages
2. Add rows
3. A new and empty row should be added to the selected position and the first cell from the same row should get focused.
> RGRIDT-843: Fixing add rows when changing pages

- code/src/WijmoProvider/Features/ColumnPicker.ts
In the continuation of the discussion started in the [components forge page](https://www.outsystems.com/forums/discussion/70842/option-mandatoryongrid/), please find below the required code for this functionality.
* The Data Grid is missing the ability to avoid the end-user from hiding a specific column, by making the check box of the respective column disabled, as the image below shows:
* A new boolean field was added to the optional configs structure
* This new boolean will then set the check box of that column as disabled throught the 'formatItem' callback.
* That will add disabled attribute to the checkboxes of the items that are being passed with the property 'isRequired' as true
1. after update outsystems module, pass a column with the parameter 'isRequired' as 'true' and other(s) …
> Added logic to disable mandatory column's checkboxes

- code/src/GridAPI/ContextMenu.ts
- code/src/OSFramework/Configuration/Column/ColumnConfigDropdown.ts
- code/src/OSFramework/Feature/IDirtyMark.ts
- code/src/OSFramework/Grid/AbstractGrid.ts
- code/src/WijmoProvider/Columns/DropdownColumn.ts
- code/src/WijmoProvider/Features/DirtyMark.ts
This PR is for Dropdown dependency columns
* There was no way to add dependency between dropdown columns.
* Created parentBinding attribute on dropdown config.
* Created datamap.getDisplayValues method to change values according to parent.
* Made some changes in DirtyMark feature in order to apply dirtyMark.
* Adjusted _validateBindings method, to validate parentBinding from dropdown columns as well.
* Fixed eslint on contextMenu api.
Automated tests have been created and are waiting for approval.
> RGRIDT-780: Dropdown dependency columns

- code/src/OSFramework/Feature/IExport.ts
- code/src/WijmoProvider/Features/Export.ts
This PR is for adding the ability for developers to provide the filename with which the excel/csv file will be exported with.
* The name of the excel/csv was hardcoded in the code
* A new input parameter was added to the feature export, name "Filename", with default value "DataGridReactive".
* A new function was created to handle the name properly
1. Add a filename in the ContextMenu option "Export to Excel"
2. Validate that the file exported has the filename + extension passed in OutSystems
3. Leave the filename field empty
4. Validate that the output file has the filename 'DataGridReactive' + extension.
> RGRIDT-861: Adding the ability to export with a specific file name.

- code/src/GridAPI/ContextMenu.ts
- code/src/WijmoProvider/Features/Selection.ts
This PR is for RGRID-735: GridAPI.Selection doesn't return the correct values
* When playing with the grid, sometimes the API return more selected rows count than expected.
* Review the output for getSelectedRows() method in Selection.ts under WijmoProvider\Features 
* Return only unique indexes (check if there are duplicated indexes)
*  Duplicate indexes could be returned when the mouse and ctrl was used for selection
1. Load the page
2. Hold Ctrl pressed
3. Click and row2 and drag it to row3
4. Click on "Get selected rows count"
5. The API returns 4 instead of 2.
- Issue https://www.screencast.com/t/5u6EdVft
- With the change: https://www.screencast.com/t/862Gn4ad7p
> RGRID-735: Review getSelectedRows function to only return unique identifiers.

- code/src/WijmoProvider/Grid/RowMetadata.ts
*  Due to Calculated Columns code, the row are now Proxy and hasOwnProperty hasn't been exposed
* Changed hasOwnProperty to [ ]
1. Open Save Changes sample
2. Delete product name in first row and click Save Changes
3. No error should appear
> Changed hasOwnProperty to [ ]

- code/src/WijmoProvider/Columns/DropdownColumn.ts
* Dropdown column dependency was only work if we changed parameters.
* Changed where displayValues is called.
1. 
> RGRIDT-871: Change display values was being called in a wrong place

- code/src/GridAPI/Cells.ts
- code/src/OSFramework/Feature/IValidationMark.ts
- code/src/WijmoProvider/Columns/DropdownColumn.ts
- code/src/WijmoProvider/Features/ValidationMark.ts
This PR fixes dropdown dependency and setCellData
* Dropdown dependency child was not working properly. 
* SetCellData was calling validateRow which was causing a loop.
* Adjusted dependency child handlers.
* Created validateCell that is called on setCellData API.
> RGRIDT-873: Dependencies

- code/src/WijmoProvider/Features/ColumnFilter.ts
This PR is for fixing add rows with calculated columns
* It was not possible to add rows when there was a calculated column
* Changed isGridFiltered method.
> RGRIDT-874: Fixing add rows with calculated columns

- code/src/WijmoProvider/Features/ColumnFilter.ts
This PR is for fixing add rows with calculated columns
* It was not possible to add rows when there was a calculated column
* Changed isGridFiltered method.
> RGRIDT-874: Fixing order

- code/src/GridAPI/GridManager.ts
This PR is to add a method to return all of the IDs of the grid in the page.
* There was no way to obtain programmatically the IDs of the Grids in the page
* Added a method to return the IDs from the Maps map.
> RGRIDT-875: Adding method to Grid API

- code/src/GridAPI/ContextMenu.ts
- code/src/WijmoProvider/Columns/ActionColumn.ts
- jobs/tests/features.txt
This PR is to remove osrowmetadata in the action column click event
* osrowmetadata in the action column click event was being added to the event data
* osrowmetadata in the action column click event was removed to the event data
1. Open Sample
2. Click the details cell in any of the rows
3. Check the Raw data in Test Results and see that osrowmetadata is not present
Before:
After:
> RGRIDT-891 - Removing osrowmetadata in the action column click event

- code/src/GridAPI/ColumnManager.ts
- code/src/OSFramework/Configuration/Column/ColumnConfig.ts
- code/src/OSFramework/Configuration/Column/ColumnConfigGroup.ts
- code/src/OSFramework/Configuration/IConfigurationColumn.ts
- code/src/OSFramework/Feature/ExposedFeatures.ts
- code/src/OSFramework/Feature/IValidationMark.ts
- code/src/WijmoProvider/Columns/DropdownColumn.ts
- code/src/WijmoProvider/Features/ColumnFilter.ts
- code/src/WijmoProvider/Features/ToolTip.ts
- code/src/WijmoProvider/Features/ValidationMark.ts
* The Column header tooltips were static, displaying the cell content.
* Add a parameter to the column config, where the developer can customize the tooltip content.
1. Fill the new Column Parameter with some text;
2. Check the tooltip hovering the column header; 
3. Fill the new Column Parameter on another Column with html;
4. Check the tooltip content, it shouldn't process the html (security);
5. Fill the new Column Parameter on another Column with an id;
6. Check the tooltip content, it should clone the content of the target id;
> RGRIDT-877 - Possibility to have custom column header tooltips

- code/src/GridAPI/Rows.ts
- code/src/OSFramework/Feature/IRows.ts
- code/src/WijmoProvider/Features/Rows.ts
- jobs/tests/features.txt
This PR fixes GetRowData when Grid is Single Entity.
* GetRowData was not working properly on grids with single entity.
* Created method that check is grid is single entity or not and returns dataItem from row.
> RGRIDT-894: Fixing GetRowData

- code/src/OSFramework/Grid/AbstractDataSource.ts
- code/src/OSFramework/Grid/AbstractGrid.ts
- code/src/OSFramework/Interface/IDataSource.ts
- code/src/WijmoProvider/Columns/ActionColumn.ts
- code/src/WijmoProvider/Grid/RowMetadata.ts
This PR is for improving the way metadata is being removed from the lines when they are being returned to the OutSystems side.
* When the action column link was clicked, the osRowMetadata was being removed from the actual line, causing the dirty marks, errors and other css classes to be removed in the line next refresh (i.e. after scroll).
* The metadata information, was not being removed when the API GetChangedLines was called. 
* The action column, now performs a clone of the line before removing the metadata and returning it
* The action column, additionally invokes the method `clear` of the `RowMetadata` object that knows how to remove the metadata.
* The data source (AbstractDataSource), is now aware of who the parent grid is, and in the method `_getChangesString` now invokes the …
> RGRIDT-923: Improving the way that osRowMetadata is removed

- code/src/WijmoProvider/Features/DirtyMark.ts
* There was a bug that when you selected the same value on a dropdown column, the dirty mark appeared. The same happened for date columns, where altering the original value and selecting the original value made the dirty mark appear.
* Created a flag to see if the value was from a dropdown column and added one more comparison for date columns.
1. 
> RGRIDT-852: Fixing dirty mark for dropdown and date columns

- code/styles/Grid.css
This PR is for adjusting header color
* With group columns, the column header had alternative color.
* Removed alt color from column headers.
> Removing header alt

- code/src/GridAPI/GridManager.ts
- code/src/OSFramework/Feature/IValidationMark.ts
- code/src/WijmoProvider/Features/Rows.ts
- code/src/WijmoProvider/Features/ValidationMark.ts
If we had one invalid line and removed it from the grid, the line would appear on InvalidLines and RemovedLines on GetChanges method. This PR addresses this issue, by setting all rows valid after they are removed.
* If we had one invalid line and removed it from the grid, the line would appear on InvalidLines and RemovedLines on GetChanges method. 
* Created new method to set row status and turn rows valid after deletion
1. Turn a row invalid and then remove it.
2. Call GetChanges API.
3. InvalidLines JSON should be empty
> RGRIDT-973: Set rows valid after deletion

- code/src/OSFramework/Configuration/Column/EditorConfigNumber.ts
- code/src/WijmoProvider/Columns/NumberColumn.ts
This PR adds hasThousandSeparator property to number columns
* It was not possible to have a column with year, because of the thousand separators. The year 2021 would become 2,021.
* Added a property that indicates whether or not the number column should have a thousand separators.
> RGRIDT-994: Adding has thousand separator property

- code/src/WijmoProvider/Columns/NumberColumn.ts
There was a bug when changing properties for the number column, as the hasThousandSeparator wasn't being assigned.
> RGRIDT-994: Fixing has thousand separator change property

- code/src/GridAPI/Pagination.ts
- code/src/OSFramework/Enum/ErrorCodes.ts
- code/src/OSFramework/Feature/IPagination.ts
- code/src/OSFramework/OSStructure/ReturnMessage.ts
- code/src/WijmoProvider/Features/Pagination.ts
- code/src/WijmoProvider/Features/Rows.ts
This PR adds GetCurrentPage and SetCurrentPage client actions onto our module.
* Adjusted GetCurrentPage API method so it returns error messages, whether or not the operation was successful, and the current page index as well.
* Created SetCurrentPage API method, that returns error messages and whether or not the operation was successful.
* Created ReturnMessage Structure and error code enumerator.
* Adjusted AddRows and RemoveRows so they use the previously mentioned structure and enum.
1. Go to sample
2. Change pages and press the GetCurrentPage button
3. It should show the current page index on the input
1. Go to sample
2. Press the SetCurrentPage button
3. It should change to the 4th page.
> RGRIDT-901: Adding GetCurrentPage and SetCurrengPage methods

- code/src/OSFramework/Grid/AbstractDataSource.ts
This PR fixes a bug on addNewRows
* We were setting keyBinding attribute into data item even if the grid didn't have a key binding defined by the user. 
* Added a check if there is key binding.
Automated test Get Changed Lines
> RGRIDT-1010: New rows won't have key binding if it wasn't set

- code/src/WijmoProvider/Columns/CurrencyColumn.ts
This PR fixes applied symbol being lost after changing decimal places
* ![symbolBug](https://user-images.githubusercontent.com/3113318/134867241-3326ba4a-dace-4aaa-87d7-65106eeabee1.gif)
* When symbol is changed, we update editorConfigs.
* [] requires changes in OutSystems (if so, provide a module with changes)
> RGRIDT-1011: Fixing applied symbol being lost after changing decimal places

- code/src/WijmoProvider/Helper/Translation.ts
This PR fixes a bug on wijmo's side that messes up the grid's language resources.
* Grid behaves in a different way when English culture file is imported
* If English language culture is imported, we ignore it.
> RGRIDT-1012: Fixing language

- code/src/WijmoProvider/Features/Pagination.ts
This PR is for fixing the asynchronous behavior in the pagination case.
* Since invoking the handlers of the events became asynchronous the moment in which we append to the events of the provider,  became different. This caused the handlers to lose the first event of the provider. leaving the pagination placeholders empty.
* Just like when someone is trying to listen to the OnInitialize of the grid and the event has already happen, we now do the same, and trigger the handler upon adding it, if both the placeholder and the provider already has a value.
1. Enter in a page using the grid with pagination
2. Check if the fields are filled up:
> Fixing asynchronously behavior with pagination

- code/src/WijmoProvider/Features/RowHeader.ts
- code/styles/Grid.css
* When the grid has checkbox, we disable clicking on row header number
* Adjusted checkbox CSS.
* Added ability to fat-finger checkbox.
* When a row is checked, all column headers are now selected. 
1. Try to click the first-row header.
2. It should not do anything.
1. Check any row.
2. Row should be painted.
3. Column headers should be painted as well.
1. "Fat-finger" a checkbox.
2. Row should be checked.
1. Cell selection should still be possible.
> RGRIDT-1037: Adjusting grid behavior when it has checkbox

- code/src/@types/wijmo-5.20212.808-rc/cultures/wijmo.culture.ar-SA.d.ts
- code/src/WijmoProvider/Helper/Translation.ts
This PR is adding the code to support ar-SA language. It is related with the issue raised in this [thread in OutSystems forum](https://www.outsystems.com/forums/discussion/72980/reactive-data-grid-arabic-support/). Special kudos to [Ahmad Abd-Allah](https://www.outsystems.com/profile/dcz3t7fakl/) for fixing the translations to "ar-AE" and providing the "ar-SA" translations. 
* Although the language file, was already available in the module, the code, was still not loading the correct translation, for missing the case for it.
* Added the case for the "ar-SA" language
1. Go to the test page
2. Change to the locale to ar-SA
3. See the grid text getting correctly translated.
> Adding the code to handle "ar-SA" language

- code/src/WijmoProvider/Features/ColumnFilter.ts
This PR is for a bug fix reported on the [forum](https://www.outsystems.com/forums/discussion/74212/adding-row-when-using-dependant-dropdowns-gives-error/) by [Bård Indredavik](https://www.outsystems.com/profile/p6p2u4tgiv/).
* Whenever we tried to add rows on the grid with dependent dropdowns, an error was thrown. This was happening because the grid behaved as if the filters were applied.
* Added an extra validation on the filter test.
* Removed wrong use of GridAPI on wijmoProvider.
1. Open the context menu and add row.
2. Row should be added.
> RGRIDT-1051: Fixing issue when adding rows and removing wrong use of API

- code/src/WijmoProvider/Features/RowHeader.ts
* The first-row header column was not centered.
* Adjusted column alignment.
1. Grid should have both row headers aligned in the center.
> RGRIDT-1037: Adding align center to rowheader column

- code/src/WijmoProvider/Features/RowHeader.ts
- code/src/WijmoProvider/Features/Selection.ts
This PR adjusts the necessary methods to ensure row addition/removal respects cell selection and row checkbox selection.
* With the newly added feature of checkbox, whenever we had a row checked and a cell on the same row selected, the grid considered there were two selections, and it would add/remove two rows.
* Adjusted getProviderAllSelections method to remove intersection between checkedRows and cellSelection from same rows.
* On a previous task, the grid's selection mode was set to CellRange when we had Checkbox. This mode didn't allow us to select multiple cells with CTRL. Switched back to MultiRange. 
1. Check a row.
2. Select a cell on the same row.
3. Open the context menu and add a row.
Expected result: Only one row should've been added.
1. Check a row.
2. Select a cell from …
> RGRIDT-1039: Add/remove rows according to selection/checkbox

- code/src/WijmoProvider/Features/ConditionalFormat.ts
This PR adjusts the conditional format to work with null dates.
* It seems that prior to 1911 time zones were different from today. Javascript respects these rules, so whenever we compared dates from 1900 (null date) a weird timezone was being applied, making it impossible to compare the values and apply conditional format.
* Adjusted the dates have the correct timezone applied on dates prior to 1911;
1. Open sample
2. Set dates on the first row according to column headers. Eg.: Column Header Null Date -> 01/01/1900
> RGRIDT-1056: Adjusting conditional format to work with null dates

- code/styles/Grid.css
* Checkbox column had 'fat-finger' applied as well.
* Adjusted CSS so only checkbox from row header has 'fat-finger'
1. Fat-finger row header checkbox.
2. Row should be checked/unchecked
1. Fat-finger checkbox from the column.
2. Nothing should happen.
> RGRIDT-1037: Checkbox column was being affected by css

- code/src/GridAPI/Selection.ts
- code/src/OSFramework/Feature/ISelection.ts
- code/src/OSFramework/OSStructure/RowData.ts
- code/src/WijmoProvider/Features/Selection.ts
* Added new GetCheckedRowsData API method.
* Created new CheckedRowData OSStructure, since checked rows don't have row index.
1. Check a row on the first page 
2. Change pages
3. Check another row
4. Press the GetCheckedRowsData button
Expected: Both rows' data should appear.
> RGRIDT-1040: Adding GetCheckedRowsData 

- code/src/OSFramework/Feature/ISelection.ts
- code/src/WijmoProvider/Features/Selection.ts
Limiting equalizeSelection to work only if grid doesn't have checked rows
* Since we decided to follow wijmo's behavior (only copy checked content) when dealing with Copy, checkbox, and cell selection, whenever we tried to copy data from a grid that had checked rows and cell selection, the grid was equalizing the selection, but when we pasted the content, only the checked row was there. This was misleading, as it seemed everything would be copied.
* Added an extra condition on equalizeSelection method to check if grid has checked rows. If it does, we don't want to equalize.
1. On Grid's without checkbox, select a cell from one column and then select a cell from a different row and column.
2. Press control C
3. Grid should have equalized the selection
1. On Grid's with checkbox, select a …
> RGRIDT-1062: Equalize selection was working when we had checked rows.

- code/src/OSFramework/Configuration/Column/ColumnConfigDropdown.ts
- code/src/WijmoProvider/Features/ConditionalFormat.ts
This PR adds conditional format to dropdown columns.
* There was no conditional format for dropdown columns
* Added conditional format for dropdown columns
* Changed way value is passed for conditional format evaluation.
1. Dropdown Cells containing 'phone' should have background-red .
2. If you change the Dropdown class input to background-blue, the cells should change as well.
> RGRIDT-1079: Adding conditional format to dropdown

- code/src/OSFramework/Configuration/Column/ColumnConfigCheckbox.ts
- code/src/WijmoProvider/Columns/CheckboxColumn.ts
- code/src/WijmoProvider/Columns/Factory.ts
This PR  adds format to dropdown columns.
There was no conditional format for dropdown columns
- Added conditional format for checkbox columns
- Changed way value is passed for conditional format evaluation.
1. Checkbox Cells containing true should have background-green.
2. If you change the Checkbox class input to background-blue, the cells should change as well.
> RGRIDT-1065: Adding checkbox conditional format

- jobs/azure-pipelines-template.yml
Recently, Azure started using Node v16 as default. This change broke our tests pipeline because a library called jasmine only works for versions prior to 14. 
* Defined specific node versions to be used on pipeline
> RGRIDT-1093: Setting node specific versions

- code/src/OSFramework/Enum/ErrorCodes.ts
- code/src/WijmoProvider/Features/Rows.ts
This PR is for a [issue ]([Data Grid Reactive] AddNewRows and RemoveSelectedRows actions always returning false in output parameter)reported on forum.
* Add/Remove rows were always returning false because on our client actions our success output parameter is set as 
* Added success code.
1. Add row.
2. Success message should be shown on green alert.
> RGRIDT-1094: Adding success code to Add/Remove row

- code/src/OSFramework/Grid/AbstractDataSource.ts
This PR fixes IsSingleEntity returning wrong value on empty grids with multiple entities.
* Empty grids with multiple entities were considered to be single entity.
* Check metadata keys to determine if grid is single entity or not.
> RGRIDT-1099: GetChangedLines throw errors on empty Grid that has multiple entities

- code/src/WijmoProvider/Features/ValidationMark.ts
This PR fixes a bug where an error was thrown when we used undo/redo after deleting rows.
* When we used undo/redo after deleting rows, the Validation mark feature was being triggered with the row object. This lead to multiple errors.
* Added a condition on Validation mark undo/redo handlers to check whether or not the old state was an object. 
1. Select rows
2. Press remove select rows
3. Press ctrl z
4. Press ctrl y
Expected result: Rows should have been deleted and no error should be thrown on the console.
> RGRIDT-757: Fixing undo/redo on delete row

- code/src/OSFramework/Event/Grid/GridEventType.enum.ts
- code/src/OSFramework/Event/Grid/GridEventsManager.ts
- code/src/OSFramework/Event/Grid/GridOnDataChangeEvent.ts
- code/src/OSFramework/OSStructure/DataChanges.ts
- code/src/WijmoProvider/Features/Rows.ts
This PR adds OnDataChange event that is triggered whenever a row is added/deleted, returning, for now, the total number of rows the grid has.
* On an empty grid, the  “We couldn't find any data to show here”  was always shown, even if the user added a new row.
* Added a new Event that is triggered whenever a row is added/deleted, returning, for now, the total number of rows the grid has.
* Used the returning value to update HasData attribute on our grid.
1. Add row
Expected:  “We couldn't find any data to show here” should disappear.
1. Add row.
2. Delete row.
Expected: “We couldn't find any data to show here” should be displayed
> RGRIDT-1098: Adding new data change event

- code/src/WijmoProvider/Features/Rows.ts
This PR adds the necessary changes for the grid to trigger DataChange event on row insertion/deletion undo and redo.
* ![RGRIDT-1098](https://user-images.githubusercontent.com/3113318/146960070-85842c6b-2cb9-4df6-a6f1-a7f64f338898.gif)
* Created GridRemoveRowAction in order to override wijmo's default undo/redo method of row deletion.
* Added event trigger on GridInsertRowAction and GridRemoveRowAction
Test Steps
1. Add row
2. Control z
Expected: “We couldn't find any data to show here” should appear.
1. Add row.
2. Delete row.
3. Control z
Expected: “We couldn't find any data to show here” should not be displayed
> RGRIDT-1098: Triggering change data event on undo/redo of row insertion/deletion

- code/src/GridAPI/Filter.ts
- code/src/OSFramework/Feature/IColumnFilter.ts
- code/src/WijmoProvider/Features/ColumnFilter.ts
- code/src/WijmoProvider/Helper/FilterFactory.ts
This PR adds a client action that will allow grids with server-side pagination to filter text/dropdown columns by value. The client action will populate the filter list with all possible values.
1. Filter text column by value.
2. All unique values should be displayed.
3. Select a value.
Expected: Filter should work
1. Filter dropdown column by value.
2. All unique values should be displayed.
3. Select a value.
Expected: Filter should work
> RGRIDT-1097: Adding SetColumnFilterOptions

- code/src/WijmoProvider/Features/DirtyMark.ts
This PR fixes a bug when deleting a is required date column.
* There was a [bug ](https://www.outsystems.com/forums/discussion/75258/data-grid-reactive-console-error-when-isrequired-property-for-date-datetime-c/) reported on forum. Whenever we have isRequired on Date/Datetime columns, cell deletion would throw an error.
* Adjusted isDirtyMark logic
1.  To focus/select the cell, click on any Date  column which has value.
2. Press Delete key from keyboard.
> RGRIDT-1115: Fixing is required on date columns

- code/src/WijmoProvider/Features/Pagination.ts
This PR fixes a bug where pagination records didn't update when grid showed no data.
* Whenever the grid didn't display any data, the pagination records were not updating. 
* Fixed the if condition. We were checking for the page records value explicitly and since it came with 0, which is falsy.
* Adjusted rowStart and rowEnd properties as well.
-Search for a name already present in the records.
-Check the number of records.
-Search for a name not present in the list of records.
-The number of records should get updated to show 0.
> RGRIDT-1121: Pagination records didn't update

- code/src/OSFramework/Event/Column/ColumnEventsManager.ts
- code/src/OSFramework/Event/Column/OnCellValueChange.ts
- code/src/OSFramework/Feature/IColumnSort.ts
- code/src/OSFramework/Helper/AsyncInvocation.ts
- code/src/WijmoProvider/Features/ColumnSort.ts
This PR adds a new way to handle onCellChange event when a column is sorted.
* Whenever we had a column sorted and did some validation on the cellChange event, the validation mark was misplaced. This happened because we handled the callback async, which means that our validation happened after Wijmo's sort event.
* Created a new method to see if the column is sorted.
* Check if the current cell's column being changed is sorted, if it is we handle the callback in a sync way, otherwise we handle it async (default way)
1. Sort the Price column
2. Change the value (must be inferior to 100)
3. The reorder is made
Expected: The error is being presented on the line where our new value was reordered
> RGRIDT-1122: OnCellChange is sync when column is sorted

- CODEOWNERS
- code/src/OSFramework/Configuration/Column/ColumnConfig.ts
- code/styles/Grid.css
This PR fixes two bugs that happened on IOS devices. One of them is that action columns with fixed text containing HTML elements were not being clicked. The other is that Grid was not being rendered on IOS versions prior to 13.4, [due to replaceAll not being supported](https://caniuse.com/?search=replaceAll)
* Adjusted CSS to support Action Column HTML elements on fixed text.
* Changed ReplaceAll to replace
1. Open sample on IOS device
2. Click on a pencil on any row
3. The Raw data table should be filled with data from the clicked row.
###
1. Open sample on IOS device with version prior to 13.4
2. Grid should render
> ROU-2948: Fixing action column link not working on IOS

- code/src/GridAPI/Cells.ts
- code/src/OSFramework/Enum/ErrorCodes.ts
- code/src/OSFramework/Feature/IValidationMark.ts
- code/src/WijmoProvider/Features/ValidationMark.ts
This PR is for the new ApplyRowValidations client action. 
* Since we already had the ValidateRow method, I only adjusted it to return the proper feedback codes.
1. Add a new row using the context menu.
2. Press Change Cell Button
Expected: New row should have invalid marks.
> ROU-2907: Adjusting ValidateRow method

- code/src/WijmoProvider/Features/Rows.ts
This PR fixes an issue where GetChangedLines was returning wrong values on removedRows. This was a side effect introduced on #176 
* RemovedRows was returning datasourceIdx along with the dataItem.
* Added only dataItems on collectionView.itemsRemoved.
1. Select a row
2. Press Remove SelectedRows button
3. Press GetChangedLines button
Expected: The returning JSON should not have datasourceIdx
> ROU-3021: Fixing issue where removedRows would return index

- CODEOWNERS
This is commemoration PR, in which @bmartinho and @tmbp95 will be freed from the responsibility of *owning* this repo.
Their contribution wasn't limited to changes in this repo, for it doesn't reflect everything that makes a software good: thinking, designing, creating, testing the best solutions for the end-user - the developer.
This being said, have the final honor to approve this PR @bmartinho and @tmbp95 !
Good riddance!
> Changing code owners

- code/src/GridAPI/Rows.ts
- code/src/OSFramework/Enum/ErrorMessages.ts
- code/src/OSFramework/Grid/AbstractDataSource.ts
- code/src/WijmoProvider/Features/Rows.ts
This PR fixes a bug on Grids that are not using ArrangeData action to serialize data. Since the grid didn't have metadata, an error was thrown.
* If there is no metadata and there is data on our dataSource, retrieve items from the first item of dataSource.
1. Open the context menu
2. Add a new row
Expected: New row should be added and it all columns should be working properly.
> ROU-3067: Fixing issue where Add Row would throw error

- code/src/WijmoProvider/Features/Selection.ts
This PR is for fixing the getCheckedRowsData method when using GetCheckedRowsData + MarkChangesAsSaved + Pagination, more than one time. 
* An error was triggered: Cannot read properties of undefined (reading 'isChecked').
* Added an ?isChecked validation
1. Select a row and edit it.
2. Click Save
3. Select another row, edit it, and save again.
4. It should successfully save, without errors
https://i.imgur.com/mr6Dx9I.gif
> ROU-3088 - Fixed isChecked validation

- code/src/OSFramework/Configuration/Grid/FlexGridConfig.ts
- code/src/OSFramework/Configuration/IConfigurationGrid.ts
- code/src/OSFramework/Enum/OS_Config_Grid.ts
- code/src/OSFramework/Feature/ExposedFeatures.ts
- code/src/OSFramework/Feature/IColumnAggregate.ts
- code/src/WijmoProvider/Features/ColumnAggregate.ts
- code/src/WijmoProvider/Features/FeatureBuilder.ts
- code/src/WijmoProvider/Grid/FlexGrid.ts
This PR created a new input parameter for the Grid. The ShowAggregateValue parameter will add a footer on the grid where the aggregate values of a column will be displayed.
* Created a new Feature called Column Aggregate.
* Created new property called showAggregateValue.
1. Toggle on the ShowAggregateValue button.
Expected: a footer row should be added to the grid.
2. Press Set Price Aggregate button.
Expected: The column price's footer should have a value displayed in bold text. The value is the sum of all price cells.
3. Toggle off the ShowAggregateValue button.
Expected: The footer row should be removed from the grid.
4. Toggle on the ShowAggregateValue button.
Expected:  a footer row should be added on the grid and it should have value on the price column
> ROU-2855: Adding ShowAggregateValue parameter

- code/styles/Grid.css
This PR adds background color to the aggregate column footer
* When we set showAggregateValues to true, the column was hard to differentiate from others
* Added a background color to it.
> ROU-2855: Adding background color to aggregate column footer

- code/src/OSFramework/Helper/Flattener.ts
- code/src/WijmoProvider/Features/Rows.ts
This PR adds an extra validation on getRowData method
* Whenever we passed an invalid row number to the getRowData method, Cannot read properties of undefined was thrown because we didn't validate whether or not the row existed.
> ROU-3050: Adding extra validation on getRowData method

- code/src/GridAPI/ColumnManager.ts
This PR fixes a bug where GetColumnById wasn't working whenever Grid was initialized from a screen transition.
* After screen transition, GridInitialize is called before Column Destroy, which means that the first column was still present on our columns array. Since we were using Array.find method, only the first element was returned. In this case, this meant that the returned element was the column from the first screen, which was not yet destroyed.
* Changed the way we found our columns. Instead of looking for the first element, we now look for the last element.
1. Open sample.
2. Check if the column name is "I am grid 1".
3. Press GridRedirected link.
Expected: The column's name should still be "I am grid 1".
1. Open sample.
2. Check if the column name is "I am grid 1".
3. Press …
> ROU-3130: Fixing GetColumnById

- code/src/WijmoProvider/Features/ValidationMark.ts
This PR fixes an issue where MarkChangesAsSaved was not removing invalid rows from GetChangedLines.
* Whenever a row has invalid content, and MarkChangesAsSaves and GetChangedLines were called, the invalidRow was still there, even with the use of MarkChangesAsSaved with ForceCleanInvalid param set to true.
* Emptied invalidRows array whenever ValidationMark clear is called.
1. Press SetCellInvalid button. The cell should become invalid.
2. Press GetChangedLines button. The Invalid lines should contain the row containing the invalid cell.
3. Press MarkChangesAsSaved button. The cell should become valid.
4. Press GetChangedLines button. The Invalid lines should be empty
> ROU-3147: Emptying invalidRows array on clear

- code/src/WijmoProvider/Features/ValidationMark.ts
This PR is to fix an issue when using parent binding and dropdowns,  where if we opened the dropdown without doing any changes, the associated column will also change and it shouldn’t since nothing changed.
* when using parent binding and dropdowns,  where if we opened the dropdown without doing any changes, the associated column will also change and it shouldn’t since nothing changed:
Validate parent binding when no changes on the dropdown options:
1. Open Page
2. In the 'Employee department' column, open the first dropdown and click on the same option.
Expected: 
- The value on the 'Employee' remains the same "
Validate parent binding with changes on the dropdown options:
1. Open Page
2. In the 'Employee department' column, open the first dropdown and click on a different option. …
> Getting the cell data for the correct type of column

- azure-pipelines.yml
- code/src/WijmoProvider/Features/ColumnSort.ts
- jobs/azure-pipelines-reactive.yml
- jobs/azure-pipelines-template.yml
This PR fixes a bug where multi sort was breaking when used on the group panel. This seemed to happen because whenever we removed the multi sort state on the group panel column, we were removing the sort description from wijmo’s sort array and wijmo’s code breaks because it expects two sort descriptions. So whenever it tries to access the second one, it throws the Cannot read properties of undefined (reading 'ascending'). 
* Moved the deletion to the Sorted event and it seemed to work. Will run a regression to see if there is no side effect. 
1. Drag Product Name into the group panel.
2. Pressing shift sort Product Category
3. Pressing shift sort Product Name
4. Not pressing shift, sort Product name again.
Expected: Product Name should be sorted desc and the sort from Product Category …
> ROU-2898: Fixing multisort error on group panel

- code/src/WijmoProvider/Features/DirtyMark.ts
- code/src/WijmoProvider/Features/ValidationMark.ts
This PR is for OnCellValueChangeEvent of Data Grid to be fired even when two columns have the same binding
* The OnCellValueChangeEvent was not being fired when I have two columns in the data grid binding to the same attribute in the database. I set a client action as the handler to the event on one of the columns. When I changed the value of the cell of that column, the client action does not get executed. However, when I remove the other column with the same binding, the event is fired and handled by the client action as it should be.
* Change _triggerEventsFormColumn to use column index instead of column binding as input parameter
1. Add a DataGrid to the screen
2. Config multiple columns with the same binding; 
3. Add custom events to some of the columns on OnCellValueChange;
4. Check …
> ROU-3217: OnCellValueChangeEvent of Data Grid not fired when two columns have the same binding

- code/extension/DataGridUtils/Source/NET/temp_ardoJSON.cs
This PR fixes an issue where Date columns were being considered DateTime.
* Only convert values that don't have 0h 0m 0s. 
1. Null dates/datetimes should be displayed as blank.
2. Whenever you edit a Date column, a feedback message with the correct date should appear.
> ROU-3297: Fixing issue with arrange Data

- code/src/WijmoProvider/Features/Rows.ts
This PR fixes an issue where GetChangedLines was not returning values properly.
* GetChangedLines is unable to detect the first row that was added. This seems to have been introduced on #181, where rowStart returned 0 instead of 1.
* Added a protection to guarantee that the topRowIndex of newly added row is never negative.
1. Add row
2. Press save changes
3. Text area should show addedLines with an empty object.
> ROU-3361: Fixing issue with GetChangedLines

- code/src/OSFramework/Grid/AbstractDataSource.ts
- code/src/OSFramework/Grid/AbstractGrid.ts
- code/src/OSFramework/Grid/IGrid.ts
- code/src/WijmoProvider/Features/Rows.ts
This PR adds another way to check if a column should be converted to Date/Datetime.
* If we had an empty grid and added a a new row with a date format: 2020-20-12. As soon as we saved this using GetChangedLines, this column would be treated as if it were Date/Datetime, because when we were parsing the grid's data, we only looked for a regex match. So any column matching the date/datetime regex would be considered as such.
* Whenever we had an empty grid, added a new row and edited a Date/DateTime column, this value would not come on GetChangedLines. This was happening, because we were not considering empty cells on the ToJSONFormat method.
* Created Column <Key, Type> map in order to use on setData.
* Created map from metadata as well.
* These maps will add an extra …
> ROU-3366: Adding another way to check if a column should be converted to Date/Datetime

- code/src/WijmoProvider/Features/DirtyMark.ts
This PR is for fixing the DirtyMark validation, when editing an empty cell and leaving it unedited. 
Before, it was still adding a DirtyMark just by double-clicking, without hanging anything.
[if Grid has now rows or empty cells, add a new one using the button on the top right]
1. Select a empty cell
2. Double Click
3. Write nothing, leave it empty, a click outside of it, to end the editing.
https://i.imgur.com/Y85FjxU.gif
> ROU-3411 - Improved DirtyMark validation with empty cell

- code/src/WijmoProvider/Features/Rows.ts
This PR fixes an issue where Remove Row was clearing the itemsRemoved array before adding the newly removed row. This caused an issue on GetChangedLines, as it only returned the latest removed row and not the previous ones.
1. Select a row.
2. Press Remove Selected Rows.
3. Press GetChangedLines.
Expected: The Removed Count should be 1.
1. Select a row.
2. Press Remove Selected Rows
3. Press Ctrl + Z
4. Press GetChangedLines.
Expected: The Removed Count should be 0.
1. Select a row.
2. Press Remove Selected Rows
3. Press Ctrl + Z
4. Press Ctrl + Y
5. Press GetChangedLines.
Expected:  The Removed Count should be 1.
1. Select a row.
2. Press Remove Selected Rows
3. Select another row.
4. Press Remove Selected Rows
5. Press GetChangedLines
Expected: The Removed Count should be 2.
1. Select a …
> ROU-3397: Remove row was not updating itemsRemoved properly

- code/src/OSFramework/Configuration/Column/EditorConfigDate.ts
- code/src/OSFramework/Grid/AbstractDataSource.ts
- code/src/OSFramework/Grid/AbstractGrid.ts
- code/src/OSFramework/Grid/IGrid.ts
This PR adds a new method that will allow JSONSerialized Empty Grids to add new row.
*  JSONSerialized Empty Grids were not able to add new rows, because we couldn't create the new item to be parsed for the new row. This happened because this specific grid didn't have metadata or data at all. 
In order to add new rows into a wijmo Grid, we need to have a clearly defined structure similar to the dataItem itself. 
So for instance, if our Grid receives a JSON containing {Employee: { Data: {Name: ""}}}, we must pass an object containing similar to this to the new row.
* Created a new method that iterates our columns, getting the binding and creating an object similar to the dataItem.
* Also fixed an issue with DateFormat where we were returning a trailing space on DateColumns.
1. Add row
2. …
> ROU-3404: Added new method to allow JSONSerialized Empty Grids to add new row.

- code/src/OSFramework/Grid/AbstractDataSource.ts
This PR fixes an issue where GetChangedLines was not working properly on empty JSONSerialized Grids. This happened because since there was no data, the ToJSONFormat method was never called and we never define the column as date. So we never treated the date properly, because we were considering it to be Datetime
1. Add row
2. Fill Date of Birth column
3. Press SaveChanges
Expected: Date of birth should have the filled date.
> ROU-3424: GetChangedLines not working properly on empty JSONSerialized Grid

- code/src/WijmoProvider/Features/ColumnFilter.ts
This PR fixes a bug where Filter by value client action was not recognizing empty values.
1. Make a cell empty on Product Name Grid Client Side
2. Clear Column name input
3. Press FIlter By Value
Expected: Grid client side should show one row where Product Name is empty.
> ROU-3438: Fixing Filter by value

- code/src/OSFramework/Grid/AbstractDataSource.ts
This PR fixes a bug on JSONSerialized grids that were not hiding null date/datetime values
* Created a formatDate method that replaces all null date/datetime values to an empty string
1. AddRow on JSONSerialize Column
2. Fill email cell and press save all button
Expected: Row is displayed without dirty mark and DateOfBirth and UpdatedOn cells are empty.
> ROU-3429: Formatting date/datetime on JSONSerialize

- code/src/GridAPI/ColumnManager.ts
- code/src/OSFramework/Enum/ErrorCodes.ts
- code/src/OSFramework/Feature/IGroupPanel.ts
- code/src/WijmoProvider/Features/GroupPanel.ts
This PR is for an API that allows the developer to add a column to the group panel by its binding.
* In the web version of this component the columns had a parameter that allow the user to config the group panel, but we didn't offer that here until now.
* create addColumnsToGroupPanel method;
* change columnInGroupPanel, to access only public attributes;
1. Add the API to a flow;
2. Check if the datagrid changed;
3. Check if its possible to added twice the same column to the group panel;
> ROU-3025: [DataGrid] - Initial display of grid with grouping state

- code/src/GridAPI/GridManager.ts
- code/src/OSFramework/Enum/ErrorCodes.ts
- code/src/OSFramework/Feature/IUndoStack.ts
- code/src/OSFramework/Grid/AbstractGrid.ts
- code/src/OSFramework/Grid/IGrid.ts
- code/src/WijmoProvider/Features/UndoStack.ts
- code/src/WijmoProvider/Grid/FlexGrid.ts
This PR adds necessary methods for new Clear Changes client action.
* Created new methods to undo/redo all changes in Grid, so whenever the user will use our client action, we’ll undo all changes on the grid in order for them to be cleared as well.
1. Add a row
2. Edit data from a row
3. Remove a row.
4. Press ClearChanges button
5. Press GetChanged Lines button
Expected: Changes will be reverted and cleared and GetChangedLines result will be empty
> ROU-3450: Adding clear changes client action

- code/src/WijmoProvider/Features/ColumnFilter.ts
This PR is for changing the isGridFiltered validation, as whenever we use SetColumnFilterOptions, the grid stops allowing new rows to be added. This happens because we are wrongly checking if Grid is filtered.
> ROU-3379: changed isGridFiltered validation

- code/src/WijmoProvider/Features/ColumnFilter.ts
- code/src/WijmoProvider/Helper/Translation.ts
This PR fixes a bug where setting the English language was not working on Grid.
* Adjusted code to allow Grid to receive the English language.
* Created helper function to customize date operators on language load.
1. Change grid to "zh-TW".
2. Check if the grid is in Chinese
3. Change grid to "en-us"
Expected: The grid should be in English.
1.  Change grid to "zh-TW".
2. Change grid to "en-us"
3. Open the Date column filter by condition
Expected: Its options should have "(not set)", "Equals", "Is greater than", "Is greater than or equal to", "Is less than" and "Is less than or equal to"
> ROU-3242: Fixing issue on language

- code/src/GridAPI/GridManager.ts
This PR fixes an issue where Grid wasn't rendering properly after clearing data.
1. Press Clear empty String
Expected: Grid should display "We couldn't find any data to show here." and should not have any rows.
1. Press Clear []
Expected: Grid should display "We couldn't find any data to show here." and should not have any rows.
1. Press Clear {}
Expected: Grid should display "We couldn't find any data to show here." and should not have any rows.
1. Press Clear empty String
2. Press Populate
Expected: Grid should display have all rows and shouldn't display any message;
1. Press Clear {}
2. Press populate
Expected: Grid should display have all rows and shouldn't display any message;
1. Press Clear []
3. Press populate
Expected: Grid should display have all rows and shouldn't display any …
> ROU-2927: Fixing Grid clear data

- code/src/OSFramework/Feature/IDirtyMark.ts
- code/src/WijmoProvider/Features/DirtyMark.ts
- code/src/WijmoProvider/Grid/ProviderDataSource.ts
- code/src/WijmoProvider/Grid/RowMetadata.ts
This fixes an issue where GetChangedLines was returning edited lines even though the row had its original value.
* Since we add rowMetadata on the grid's dataItem, wijmo can't tell if the dataItem has been changed or not, because for them the dataItem is always different from the original value.
* Created a method that tells if Grid has dirty marks and uses that on GetChangedLines.
1. Change the Product Category on the first cell.
2. Change back to the original value.
3. Press GetChanged Lines.
Expected: Should return empty values.
> ROU-3475: Fixing issue with GetChangedLines

- code/src/OSFramework/Feature/Auxiliar/RowStyleClassInfo.ts
- code/src/OSFramework/Feature/IRows.ts
- code/src/WijmoProvider/Features/ConditionalFormat.ts
- code/src/WijmoProvider/Features/Rows.ts
This PR fixes an issue on the conditional format when we had multiple columns having a conditional format that adds the same rowClass.
* On a grid where we have a text column that is supposed to add “background-yellow” to the cell if it contains silver or grey and a column that adds “background-yellow” if the cell is less than 4000.  ![image](https://user-images.githubusercontent.com/3113318/171174793-6ec8205d-f7a6-4a4b-ba42-1cadef82cc6f.png)
* We would expect all cells to be yellow since they contain grey or silver on the Product Name or have a stock value of less than 4000. But since the last Stock cell is greater than 4000, the class is removed from the row.
* Changed the row class metadata to be a Map<ClassName, [ColumnName ]>, so that we can properly know which column has added which …
> ROU-3474: Conditional format didn't work properly with rows.

- code/src/GridAPI/Styling.ts
- code/src/OSFramework/Feature/IStyling.ts
- code/src/WijmoProvider/Features/Styling.ts
This PR adds dynamic height param to SetColumnWordWrap client action
1. Click SetColumnWordWrap (Product.Name) button
Expected: Cells on Product Name should have word wrap and their rows should have their height adjusted.
> ROU-3473: Adding dynamic height

- code/src/WijmoProvider/Features/Styling.ts
This PR adds dynamic height param to SetColumnWordWrap client action
Test Steps
Click SetColumnWordWrap (Product.Name) button
Expected: Cells on Product Name should have word wrap and their rows should have their height adjusted.
> ROU-3473: Adding dynamic auto row height

- code/src/OSFramework/Enum/RowMetadata.ts
- code/src/OSFramework/Grid/AbstractDataSource.ts
- code/src/WijmoProvider/Features/CellStyle.ts
- code/src/WijmoProvider/Features/DirtyMark.ts
- code/src/WijmoProvider/Features/Rows.ts
- code/src/WijmoProvider/Features/ValidationMark.ts
- code/src/WijmoProvider/Grid/RowMetadata.ts
This PR fixes an issue where GetRowData was returning row metadata. This PR also created a RowMetadata Enum.
1. Press GetRowData Valid
Expected: Result should not contain __osRowMetadata":{}
> ROU-3499: Fixing GetRowData

- code/src/WijmoProvider/Columns/CalculatedColumn.ts
Fixed issue where calculated columns with similar names didn't work properly.
1. Change the first cell of the Price column to 20
2. Change the first cell of In Stock column to 4
Expected: Column Sum should have 34 on the first cell, Sum1 should have 25 and Sum2 should have 26.
> ROU-3520: Calculated column

- code/src/OSFramework/Grid/AbstractGrid.ts
- code/src/OSFramework/Helper/AsyncInvocation.ts
- code/src/WijmoProvider/Grid/FlexGrid.ts
This PR fixes a bug where OnInitialize event was being triggered incorrectly on Grids. 
There were two scenarios happening: 
1. Autogenerated grids triggered the event before the columns were created. This caused many client actions to not work properly on the event, as they were doing some changes on columns.
2. In some cases, the event was triggered before the Grid was ready, which led to inconsistent behavior.
1. Both text areas should show the last column name.
2. Press F5 multiple times. And check if the names are there.
> ROU-3538: Fixing OnInitialize event

- code/src/WijmoProvider/Features/ContextMenu.ts
- code/styles/Grid.css
This PR is for fixing two issues:
1. When the grid has less rows than the available height, right-clicking to open the ContextMenu on the empty space would trigger console errors and wouldn't open the menu. This was due to trying to find the binding of a non-existent column.
2. The empty-message is absolute with z-index:1, which was preventing the right-click to open the ContextMenu to work.
> ROU-3593: Fix ContextMenu event and right click on empty-message

- code/src/OSFramework/Feature/IDirtyMark.ts
- code/src/WijmoProvider/Features/DirtyMark.ts
- code/src/WijmoProvider/Grid/ProviderDataSource.ts
This PR fixes an issue where GetChangedLines was returning two edited rows when only one was added. This was caused by inconsistency on wijmo's side, but it is now addressed here.
1. Edit Price cell on first row.
2. Open edition on Product Name cell on second row, but don't make any change and press Enter.
3. Press GetChangedLines
Expected: The result should contain only the first row.
> ROU-3592: Fixing issue with getchangedLines

- code/src/WijmoProvider/Features/ContextMenu.ts
This PR is to fix an error on the console when right-clicking on the column picker.
* Error on the console when doing right-click on the column picker:
* Added an extra validation to exclude columns without binding
1. Right-click on the column picker
2. Check that no errors are displayed on the console
> Fix error on the console when right-clicking on the column picker

- code/src/OSFramework/Column/AbstractColumn.ts
- code/src/OSFramework/OSStructure/ColumnProperties.ts
- code/src/WijmoProvider/Columns/AbstractProviderColumnEditor.ts
- code/src/WijmoProvider/Columns/DateColumn.ts
- code/src/WijmoProvider/Columns/DateTimeColumn.ts
- code/src/WijmoProvider/Columns/DropdownColumn.ts
- code/src/WijmoProvider/Columns/NumberColumn.ts
This PR fixes a bug where changing column properties would break columns that have a conditional format.
1. Change header name
Expected: Header name of the first column should change and no error should be thrown.
> ROU-3667: Fixing changeProperty

- src/Providers/DataGrid/Wijmo/Features/Rows.ts
This PR improves undo add rows performance.
* We were using collectionView.remove, which iterates over array to find item index and them eventually uses splice to remove it.
* Changed the itemsAdded removal to splice directly, since we can find out the starting index from beginning.
> ROU-3673: Improving undo add rows performance

- extension/DataGridUtils/Source/NET/ObtainMetadata.cs
- extension/DataGridUtils/Source/NET/temp_ardoJSON.cs
This PR fixes a wrong removal of prefixes on structure attributes. Example: If we had a Record List containing a Record that had attributes starting with "ST" or "EN", we were removing it.
> ROU-3764: Fixing wrong removal of prefixes on structure attributes

- src/OutSystems/GridAPI/Cell.ts
- src/OutSystems/GridAPI/ColumnManager.ts
- src/OutSystems/GridAPI/Styling.ts
This PR is for fiz the bug in SetCellData action
* SetCellData function was getting the wrong column reference when there was two grids with same columns on the page
* Instead of using the ColumnManager.GetColumnById() method, now we use grid.getColumn()
> ROU-3762: Issues when using SetCellData with several Grids with columns with the same binding

- src/OSFramework/DataGrid/Feature/ISelection.ts
- src/OutSystems/GridAPI/Selection.ts
- src/Providers/DataGrid/Wijmo/Features/Selection.ts
This PR is to add new APIs that allows the user to get the max and min of a cell selection.
* Create methods that get the value of number, currency, and calculated cells selected and calculate the min or max of it.
1. Run the APIs after a selection;
2. Check if the value is the expected;
> ROU-3733 - [DataGrid] - Client actions that return the selection min and max value

- src/OSFramework/DataGrid/Grid/AbstractDataSource.ts
- src/OSFramework/DataGrid/Helper/JSONParser.ts
This PR is for fix the bug when changing the value of a Date Column that initially has a DateTime type data assigned to it. Same issue was also happening when calling GetChangedRosw action.
* When passing DateTime attributes in a Date column and vice versa, we were getting the error `date.getTime() is not a function`.
* The GetChangedRows action was not returning the changed rows when the Datetime column with a date attribute gad it values changed.
* Inserted an assertion that check if the value that comes from a Date and DateTime columns is a string. If it is, so we convert it to a Date format.
1. Go to test page.
2. Open the Dev Tools console tab
3. Change the date of the first column
4. Check that no error has appeared in the console
5. Click in GetChangedRows button
6. Check if the …
> ROU-3885: Fix getTime bug when the date is in string format

- src/OSFramework/DataGrid/Configuration/Column/ColumnConfigAdditional.ts
- src/OSFramework/DataGrid/Types/index.ts
- src/Providers/DataGrid/Wijmo/Columns/AbstractProviderColumn.ts
- src/Providers/DataGrid/Wijmo/Columns/CalculatedColumn.ts
- src/Providers/DataGrid/Wijmo/Columns/Factory.ts
This PR is for add to Calculated Columns the functionality to handle with DecimalPlaces and HasThousandsSeparator parameters.
* Added new the parameters
* Added the logic to handle them on build
* Added the logic to handle their change in OnParameterChange
1. Go to the test page
2. Set a valid value (0 to 11) to Decimal Places
3. Click in "Update Decimal Places"
Expected: The values in the calculated columns are updated to the new decimal places number.
1. Go to the test page
2. Switch the "Add thousands separator" switch button
Expected: The values in the calculated columns react adding or removing the thousands separator.
> ROU-3891: Decimal places not working properly on calculated columns

- src/Providers/DataGrid/Wijmo/Features/ValidationMark.ts
- src/Providers/DataGrid/Wijmo/Grid/ProviderDataSource.ts
This PR is for fix the issue with the GetChangedLines returning an empty array when not in the first page, even with edited lines in the page, and when filter and sort were applied.
* In src\Providers\DataGrid\Wijmo\Grid\ProviderDataSource.ts:
* In _getDirtyEditedItems():
* itemsSource.sourceCollection.findIndex() returns the index based on all data, not only in the current view.
* isRowDirty() method was returning false when the rowIndex >= number of rows in the view, because the _hasMetadata inside the _isDirtyRow() method only validates the metadata of the rows in the current view.
* Because of other issues found during the development of this task, it was necessary to rollback a previous fix related to GetChangedLines (ROU-3592). As a consequence, the bug that the fix solved, is …
> ROU-3936: Fix GetChangedLines not working when not on the first page

- src/Providers/DataGrid/Wijmo/Columns/DropdownColumn.ts
- src/Providers/DataGrid/Wijmo/Features/ValidationMark.ts
This PR is for fix the OnCellValueChange is not triggering with the original value.
* When changing the cell value to a different value and then returning to its original value, the OnCellValueChange is not triggered.
* When opening and closing the dropdown, it mark the cell as changed and it shouldn’t.
* When erasing the cell value using the delete key, the OnCellValueChange was not being triggered
* In _cellEditBeforeEndingHandler in ValidationMark.ts, added new validations to check if the delete key was pressed and get the right currentValue.
* Since we are already validating if the value changed or not, we can use the `e.cancel` to trigger or nor the OnCellValueChange event in _cellEditHandler()
> ROU-3950: Investigate the reason why the columns OnCellValueChange is not triggered with the original value

- src/Providers/DataGrid/Wijmo/Features/DirtyMark.ts
This PR is for fix the dirty mark appearing when the dropdown cell returns to its original value. 
* Added a validation for when the values compared are from different types (int and string).
> ROU-3994: Dirty mark appear when the dropdown cell returns to its original value

- src/Providers/DataGrid/Wijmo/Columns/DropdownColumn.ts
This PR is for fix parent dropdown not erasing the child when returning to its original value
* The parent dropdown handler was not erasing the child value when oldValue === newValue
* Removed the code that erases the dropdown child cell from the if that verifies if the oldValue is different than the newValue.
* Now it also erases the values when the oldValue is equal to the newValue.
1. Go to the DropdownDependency test page 
2. Change the parent dropdown of the first row to different value
3. Change the child dropdown of the first row to a different value
4. Change the parent dropdown of the first row to the original value
5. Check if the child dropdown of the first row is empty, has a dirty mark and is invalid.
> ROU-4011: Fix parent dropdown not erasing the child when returning to its original value

- src/Providers/DataGrid/Wijmo/Columns/NumberColumn.ts
This PR is for add warning message for when NumberColumn's MaxValue is smaller than MinValue
* When using a MinValue bigger than 0 and keep the MaxValue unset, the input value in the cell is being forced to the MinValue.
* It occurs because the MinValue and MaxValue default value are 0. 
* Added a warning message to warn when the MinValue is bigger than the MaxValue.
1. Add a Number Column
2. Set the MinValue and the MAxValue in a way that MinValue > MaxValue.
3. Check if the warning message appears on DevTools console.
> ROU-4049: Issue in number columns when not setting one of the bounds

- src/OSFramework/DataGrid/Configuration/Column/EditorConfigNumber.ts
- src/OSFramework/DataGrid/Types/index.ts
- src/Providers/DataGrid/Wijmo/Columns/NumberColumn.ts
This PR is for fix DecimalPlaces not updating correctly the MinValue and MaxValue limits through OnParametersChanged.
* When maxValue > MaxNonDecimalValues[decimalPlaces], maxValue was overwriten by MaxNonDecimalValues. This way, it was not possible to assume maxValue original value, when it went back to MaxNonDecimalValues < maxValue. The same was occurring for minValue and minPerDecPlaces
* Two new attributes maxPerDecPlaces and minPerDecPlaces where added to EditorConfigNumber class. They store the maximum and minimum value according to the decimalPlaces set, respectively.
* The minValue and maxValue keep their original value unless and OnParametersChange event occurs
* In EditorConfigNumber.getProviderConfig, it is being validated if minPerDecPlaces or minValue should be assigned to …
> ROU-4049-2: Issue in number columns when not setting one of the bounds

- src/Providers/DataGrid/Wijmo/Features/Selection.ts
This PR is for fix the selection not getting all the rows and ranges correctly.
* The getProviderAllSelections was not returning the rows selected using SetRowAsSelected method in a grid without checkboxes.
* The getProviderAllSelections was not returning the correct ranges when a range intersect the selected row via checkboxes in a grid with checkboxes.
* Implemented a solution that merge the selected rows to the ranges removing the duplicated cells when an intersection between row and range is found.
* Change the behaviour to always get all the ranges and rows selected in a grid with checkboxes.
Test 1: 
1. Select some rows of the DataGrid using SetRowsAsSelected()
2. Call GetAllSelections, GetAllSelectionsData, GetSelectedRowsCount, GetSelectedRowsData, GetSelectionAverage, …
> ROU-4065: SetRowAsSelected not selecting the rows as expected

- src/Providers/DataGrid/Wijmo/Features/TabNavigation.ts
This PR is for change the default TabNavigation behaviour.
* There was an accessibility issue when using the Tab key inside the Grid. Once inside the Grid it is not possible to get out using the Tab key.
* In Service Studio, changed the allowKeyTabNavigation internal config value from "True" to "False", so the default behavior is the arrow navigation inside the Grid, and the Tab key is used to get in and out of it.
* In the code, changed from "Cycle" to "CycleOut" mode in TabNavigation feature, that makes it possible to use the tab navigation and get out of the Grid using Tab key.
1. Go to a page with DataGrid Reactive.
2. Check if it is possible to get in and out the Grid using Tab key and navigate inside it using the arrow keys.
> ROU-4077: Allow developers to control  the Tab key action for accessibility reasons

- src/Providers/DataGrid/Wijmo/Features/ToolTip.ts
This PR is for prevent the tooltip to be set with its column preview when column name match with tooltip text. Corrected the HeaderTooltip not being set correctly when the grid has repeated binding in different columns
* When the column name matches with tooltip text, the tooltip was set with its column preview.
* When two columns have the same binding, the header tooltip was not set correctly for one of them.
* Sometimes the header tooltip was not appearing unless some modification was made in the column (resizing the column for example).
* Add a condition to check when the column name matches the tooltip text, if true, then the column header will be set to the tooltip.
* Instead of using Tooltip.setTooltip() the tooltip in MouseOver event, now we are using Tooltip.show().
* Instead of …
> ROU-4150: Issue in column HeaderTooltip when column name match with tooltip text

- src/Providers/DataGrid/Wijmo/Features/ToolTip.ts
This PR is for fix the issue with the tooltip when scrolling the page.
* When you scrolling the mouse over the cell, the hitTest return an invalid cell.
* Changed the hitTest argument from MouseEvent to the cell's HTMLElement.
1. Go to a page with a Grid
2. Open the DevTools
3. Scroll the mouse over a Grid cell
Expected: No error is raised.
> ROU-4179: Issue with HeaderTooltip when scrolling the page

- src/Providers/DataGrid/Wijmo/Features/ToolTip.ts
- src/Providers/DataGrid/Wijmo/Features/ValidationMark.ts
This PR is for fix showing invalid tooltip when cell is valid.
* The Tooltip's onMouseEnter event listener was trigger before the "wj-state-invalid" cell class is removed
* Now, instead of check if the "wj-state-invalid" is a cell class, we use the isInvalid method from the ValidationMark feature. 
1. Go to the test page
2. Click to edit a cell to an invalid value
3. Press enter
4. Click to edit a cell to an invalid value
Expected: Check that no error tooltip appears.
> ROU-4200: Showing invalid tooltip when cell is valid

- src/OSFramework/DataGrid/Feature/IUndoStack.ts
- src/OSFramework/DataGrid/Grid/AbstractGrid.ts
- src/Providers/DataGrid/Wijmo/Features/UndoStack.ts
This PR is for fix issue with undo action after Server Side search
* The undo action was happening in the wrong rows after data source refresh due to the server side search.
* Clear undo stack when the data source is updated.
1. In a grid, add a new row
2. Fill the empty cells with data
3. Perform a server side search
4. Check that it is not possible to undo any action.
> ROU-4205: Issue with undo action after Server Side search

- src/Providers/DataGrid/Wijmo/Features/ToolTip.ts
This PR is for fix the tooltip class error.
* When an invalid cell was edited to a valid value, then the error class is not properly removed from the tooltip, and all the other tooltips were displayed as error tooltips (with background red).
* Implemented the workaround provided by wijmo expert:
* Set the class attribute directly in the tooltip element.
* This implementation will be removed after wijmo release.
> ROU-4207: Tooltip errorValidation class is not removed properly

- src/Providers/DataGrid/Wijmo/Features/ValidationMark.ts
This PR is for cancel cell editing if ESC key was pressed
* When Esc is pressed while editing, it should cancel the editing, but it did not happen.
* Check if "cancel" property of wijmo.grid.CellRangeEventArgs is true in _cellEditBeforeEndingHandler. 
* If true, return; else proceed with the cell editing.
1. Go to a page with a Grid
2. Edit any cell value
3. Before finish editing, press ESC key
4. Check if the previous cell value is restored.
> ROU-4230: Escape key does not cancel cell editing

- src/OSFramework/DataGrid/Enum/ErrorCodes.ts
- src/OSFramework/DataGrid/Feature/IColumnAggregate.ts
- src/OSFramework/DataGrid/Feature/IConditionalFormat.ts
- src/OutSystems/GridAPI/ConditionalFormat.ts
- src/Providers/DataGrid/Wijmo/Features/ColumnAggregate.ts
- src/Providers/DataGrid/Wijmo/Features/ConditionalFormat.ts
- src/Providers/DataGrid/Wijmo/Features/Selection.ts
This PR is for add a new client action to apply conditional format to the aggregate row.
OutSystems.Providers.DataGrid.Wijmo.Feature:
- Fixed error not being throw for SetRowAsSelected
OutSystems.GridAPI.ConditionalFormat:
- Created SetNumberAggregateConditionalFormatting function
Providers.DataGrid.Wijmo.Features.ColumnAggregate:
- Created the _cellClasses Map to store the class to be applied to each column. The keys are the column binding and the element array os string containing the classNames to be added to the cell's aggregate.
- Implemented setConditionalFormat method:
- Responsible for check if all the conditions to add the conditional format are respected.
- Calls the addAggregateRules from Conditional Format
- Implemented addClass and removeClass methods:
- Responsible for add …
> ROU-3748: Add client action to apply conditional format to the aggregate row

- package-lock.json
- package.json
- src/OSFramework/DataGrid/Constants.ts
This PR is for update OutSystems DataGrid version to 2.12.0.
> Update OutSystems DataGrid version

- src/OSFramework/DataGrid/Configuration/Column/EditorConfigDate.ts
- src/OSFramework/DataGrid/Feature/IColumnFilter.ts
- src/OutSystems/GridAPI/Filter.ts
- src/Providers/DataGrid/Wijmo/Features/ColumnFilter.ts
This PR is to implement a way to trigger the OnFiltersChange event when using the ClearFilter.
* When using the Filters API, only the ClearFilter was not triggering the OnFiltersChange event.
* Changed ClearFilter to allow triggering OnFiltersChange event
1. Go to GridReactive_Automation_ROU4340/API_Filter
2. Clicked in Filter by Value
3. Checked that the Server Side Grid was filtered and the OnFiltersChange event triggered
4. Clicked in Filter Clear
5. Checked that the Server Side Grid got the filters cleared and the OnFiltersChange event triggered
6. Do the same using the Grid filters to filter and clear, checking that the OnFiltersChange event triggered
> Changed ClearFilter to allow triggering OnFiltersChange event

- src/OSFramework/DataGrid/Enum/ErrorMessages.ts
- src/OutSystems/GridAPI/Pagination.ts
This PR is for fixing an issue in the `moveToPage()` method that was always throwing an error.
* Even in the case of a successful call, the client action **SetCurrentPage** was throwing an error.
* Fixed the condition that was throwing the error.
1. Go to GridReactive_Automation_ROU4367/API
2. Add the page to go in the input set as 5
3. Click in "Set Current Page"
4. Check that the page changed and no error was returned
> ROU-4367: Fixed issue in moveToPage error handling

- src/OSFramework/DataGrid/Grid/AbstractDataSource.ts
This PR is for fixing the Invalid lines data when invoking the API. The API was returning  the metadata attribute, when it shouldn't:
* The code to obtain the json for invalid rows, was calling a method (`toOSFormat`) that for other changes was not occurring
* The method `toOSFormat` was wrapping the object received in an array (e.g. [dataItem]) independently on the type of dataItem
* The method `toOSFormat` will now validate before wrapping. If it's an array, as in the case of the invalid lines, it will not wrap the data item any more.
1. Access to a data grid page (e.g. `/GridReactive_Automation_InvalidLine/Validation`)
2. Make one or several lines invalid (depends on the business rules implemented, but for one, so that the line becomes invalid)
3. Invoke the api: 
```
(function(){ …
```
> ROU-4377: Invalid lines - removing attribute __osRowMetadata

- src/OutSystems/GridAPI/Language.ts
- src/Providers/DataGrid/Wijmo/Helper/Translation.ts
- src/Providers/DataGrid/Wijmo/Language/Languages.ts
This PR is for unifying how the language mechanism works in O11 and ODC.
* The language mechanism was dependent of the language (JS) files to be deployed unto the server
* In ODC, that would imply having a specific app to simply deploy the files
* The team decided to use the same mechanism to O11 as it is used in ODC
* The OS module, will now set the url for the file of each language
* The load itself, will be similar to the previous one, with the difference that the language URLs will be known before hand, instead of relying on building the url
* This also simplifies the load language API
1. Go to a page with the DataGrid and change the locale.
2. The changes should be reflected in the grid
> ROU-4373: Changing language load mechanism

- src/OSFramework/DataGrid/Event/Feature/ContextMenuEventManager.ts
- src/OSFramework/DataGrid/Feature/IContextMenu.ts
- src/OSFramework/DataGrid/Helper/CheckPlatformId.ts
- src/Providers/DataGrid/Wijmo/Features/ContextMenu.ts
This PR is for changing the column ID returned in the event OnMenuToggle. Currently was returning the uniqueId of the column. This implied that if the developer would have to use our JS apis to obtain the information that would help him in his endeavors. 
* The unique ID of the column in which the contextMenu is being displayed, was being returned. 
* Created a new function to check if the block has a default Id generated by the platform
* The ID returned now depends of:
* if the developer used auto-generated: column binding (as it was now)
* if the developer used columns: 
* defined widget name: the widget ID is returned
* didn't defined the widget name: the column unique is returned
1. Create 2 simple grids:
a. one auto generated
b. with columns, and give a widget name to one of the …
> ROU-4350: Changing context menu to return the correct Id of the column in the Toggle event

- src/Providers/DataGrid/Wijmo/Features/ContextMenu.ts
When the context menu event is opening.
This PR is for fixing the behavior in which the ContextMenu was raising the event of Toggle twice, when the ContextMenu was being open.
* The context menu was raising twice the toggle event when it was opening
* Protected the place where the event was being inadvertently raised
* The event in this place, will now only be raised when the ContextMenu is closing
1. Right click on any column - context menu opens, and the message of it opening should finish with `(1)` in the end
2. Repeat the operation to another column - the message should end with `(2)`
3. Repeat 2. - the message should end with `(3)`
> ROU-4386: ContextMenu - avoid raising twice ToggleEvent when opening

- src/OSFramework/DataGrid/Configuration/Grid/FlexGridConfig.ts
- src/OSFramework/DataGrid/Types/index.ts
This PR is for set Row and column headers to be accessible via keyboard.
* The Row and Column headers were not accessible via keyboard by default.
* Set the headersFocusability property to "All" by default allowing the Row and Column headers to be accessible.
1. Go to a page with a Grid with accessibility feature enabled
2. Check that it is possible to access the Row and Column headers via keyboard.
> ROU-4388: Improve header's accessibility

- src/Providers/DataGrid/Wijmo/Features/ContextMenu.ts
This PR is to fix an issue that caused the Context Menu to start getting duplicated Menu Items.
This occurred when an auto-generated Data Grid got the associated data source refreshed after filtering it.
* Issue caused the Context Menu to start getting duplicated Menu Items:
* Fix the code responsible to add menu items to take into consideration not adding duplicate items.
**Test Case 1 - Auto-generated**:
1. Go to ContextMenu_Autogenerated
2. Open Context Menu
3. Filter by Date Range
4. Open Context Menu
5. Check that no duplicates are displayed
**Test Case 2 - Cols;**
1. Go ContextMenu_Cols
2. Open Context Menu
3. Filter by Date Range
4. Open Context Menu
5. Check that no duplicates are displayed
s
> ROU-4413: Fix issue with Context Menu that gets duplicated Items

- src/OSFramework/DataGrid/Enum/ErrorMessages.ts
- src/Providers/DataGrid/Wijmo/Features/ValidationMark.ts
This PR is for fix ApplyRowValidation API not working for Group Columns
* In validateRow method of ValidationMark feature, the getCellData return undefined since it is not possible to get the cell data from a Group Column.
* Add an assertion to skip Group Column when validationg the row data.
1. Go to a page with a Grid with mandatory columns.
2. Add a new row.
4. Run the ApplyRowValidation Client Action for the added row.
5. Check that the row's mandartory cells are set as invalid.
> ROU-4406: Issue when applying row validation to a Grid with GroupColumn

- src/Providers/DataGrid/Wijmo/Features/ColumnFilter.ts
- src/Providers/DataGrid/Wijmo/Helper/FilterFactory.ts
- tsconfig.json
This PR is for fixing APIs `FilterByCondition` & `FilterByValue` that were not working with the checkbox column.
* When using the `FilterByCondition` API to filter CheckboxColumn, the result is empty even if there are some values in the database that match the filter.
* In the private method `_getFilterConditionValue` added a new check for the checkbox column, where the `_formattedValue` is equal to the string 'True'  of the platform. -> **This fixes the `FilterByCondition` API**
* Created a new private method `_getFilterValue` that format the value to be compared, it encapsulates the previous behavior and adds a special check for checkbox columns. -> -> **This fixes the `FilterByValue` API**
1. Open sample page
2. Use the API `FilterByCondition`, to filter the column checkbox
3. See if …
> ROU-4429: Fixing APIs `FilterByCondition` & `FilterByValue` to work with checkbox column

- src/OSFramework/DataGrid/Grid/AbstractDataSource.ts
This PR is for revert empty strings being converted in undefined.
* OS Date/DateTime fields are sent as strings, and we should parse it to the correct data type. When they are empty strings, we convert it to undefined.
* The problem is that we are doing it for all data that are empty strings, which is not necessary
* Changed the ToJSONFormat function of AbstractDataSource file to only convert to only convert empty string in undefined in two cases:
* When it is Date or DateTime columns data
* When it is an unknown data type, because it can or cannot be Date/DateTime, so we convert it to avoid errors.
1. Go to a page witha Grid to the page containing some data with empty values in Text, Date and DateTime columns.
2. Call the GetRowData Client Action for the desired RowNumber
3. Check that …
> ROU-4304: Revert empty strings being converted in undefined

- package-lock.json
- package.json
- src/OSFramework/DataGrid/Constants.ts
- src/Providers/DataGrid/Wijmo/Columns/GroupColumn.ts
This PR is for fix critical issue on version 2.12.0 on Grouped Columns
* Due to a breaking change of Wijmo's library, the collapseTo does not accept undefined anymore, triggering an error.
* In GroupColumn's _getCollapsedToBinding method, changed the return to an empty string instead of undefined.
1. In GroupColumn _getCollapsedToBinding method, changed to return an empty string instead of undefined,
> ROU-4460: Critical issue on version 2.12.0 on Grouped Columns

- src/OutSystems/GridAPI/Auxiliary.ts
- src/OutSystems/GridAPI/GridManager.ts
- src/OutSystems/GridAPI/Performance/PerformanceAPI.ts
This PR would be the first step on reducing some verbosity on DataGrid's public API methods. It creates an auxiliary function that would execute and measure the performance of a given function. Only changed GridManager, as I understand changing all APIs would make this PR tough to read/test.
* Currently our public APIs are very verbose. For each API method, we call Perfomance.SetMark and Performance.GetMeasure, while repeating the function's name a few times.
* Created an auxiliary function called MeasurePerformance that receives a functionName and the function itself and returns the output of the function, while measuring its performance.
1. Open this [sample](https://outsystemsui.outsystems.com/OutSystemsDataGridSample/SearchingData)
2. To enable performance measurements, we must call …
> Improving performance api

- src/Providers/DataGrid/Wijmo/Features/ColumnFreeze.ts
- src/Providers/DataGrid/Wijmo/Features/ValidationMark.ts
This PR is for Implement workarounds for Wijmo's issues for frozen columns and Backspace/Delete keys
* When using the BackSpace/Delete keys the OnCellValueChange event was not triggering
* When a frozen column was resized to its maximum possible width, it was not possible to resize it again.
* Now, if the Delete or BackSpace keys are used, we store the s.activeCell.textContent as the currentValue in _cellEditBeforeEndingHandler method of ValidationMark.
* Added the _afterResizeColumn method to the ColumnFreeze, which checks if the column was resized to the maximum width and resizes it in 10 pixels less than the max.
1. Go to a test page
2. Use Delete or BackSpace key to erase the cell value
3. Check that the OnCellValueChange event was triggered.
1. Go to a test page with a Grid with a …
> ROU-4481: Implement workarounds for Wijmo's issues for frozen columns and Backspace/Delete keys

- src/OSFramework/DataGrid/Configuration/Column/ColumnConfigAction.ts
- src/OSFramework/DataGrid/Configuration/Column/ColumnConfigImage.ts
- src/OSFramework/DataGrid/Enum/CellTemplateElementType.ts
- src/OSFramework/DataGrid/Enum/ColumnType.ts
- src/OSFramework/DataGrid/Event/Column/ColumnEventType.enum.ts
- src/OSFramework/DataGrid/Event/Column/ColumnEventsManager.ts
- src/OSFramework/DataGrid/Event/Column/ImageColumnClick.ts
- src/OSFramework/DataGrid/Types/index.ts
- src/Providers/DataGrid/Wijmo/Columns/Factory.ts
- src/Providers/DataGrid/Wijmo/Columns/ImageColumn.ts
- src/Providers/DataGrid/Wijmo/Helper/CellTemplateFactory.ts
This PR is for implementing the new image column.
- Added ImageColumn class
- Added ImageColumnClick event
- Added ColumnConfigImage
- Changed ActionColumnFactory to CellTemplateFactory
1. Go to a page with an Image Column
2. Check if the image is displayed
3. Check if the ClickEvent is fired when the image is clicked
4. Check if the image's alt-text and aria-label correspond to the AltTextFixed or AltTextFromBinding
> ROU-4182: New Image Column

- src/Providers/DataGrid/Wijmo/Features/Styling.ts
- styles/Grid.css
This PR is for fixing the cells and headers when using the SetColumnWordWrap API.
Now a class is added on the host element, so that the CSS exceptions have no impact in other use-cases.
> ROU-4476 - Fixed wrap styles

- src/OSFramework/DataGrid/Configuration/Column/ColumnConfigAction.ts
- src/OSFramework/DataGrid/Configuration/Column/ColumnConfigImage.ts
- src/OSFramework/DataGrid/Types/index.ts
- styles/Grid.css
- Improved code for Action column with button so it works in Firefox as well
This PR is for fix Image Column cell css
* The image was not centered in the cell when the Image column was rendered
* We were using the :has to apply CSS to the button of the Action Column which is not supported in Firefox. 
* Created the has-image-or-button class to be applied in Action column with buttons and Image Columns.
> ROU-4182: Improve Image column CSS

- src/OSFramework/DataGrid/Grid/AbstractDataSource.ts
This PR is to fix the GetChangedLines returning an error after removing and adding a new line in ODC.
* In ODC, we got an error when adding a row, removing it, and adding it again:  `TypeError: 'ownKeys' on proxy: trap returned duplicate entries`.
* This error was occurring in the [_getChangesString method](https://github.com/OutSystems/outsystems-datagrid/blob/2292d363e5c052786f9f3e6d411342e720803abe/src/OSFramework/DataGrid/Grid/AbstractDataSource.ts#L241) in AbstractDataSource when cloning items of the itemsChanged array to create a new array to be returned. 
* The error occurs because the itemsChanged array contains the proxy object referred to the data item of the added row, which contains duplicated keys for the calculated columns (one of them omitted and the other one visible).
* …
> ROU-4467: GetChangedLines returning an error after removing and adding a new line

- src/Providers/DataGrid/Wijmo/Columns/DropdownColumn.ts
This PR is to fix the issue with the dropdown column when deleting multiple cells and undoing the action.
* When deleting multiple cells of dropdown cells with dropdown dependency and undoing it, not all the child cells were being restored to their previous value. 
* This was happening because not all the undo actions were being registered as children of the first undo action.
* Instead of trying to find the action related to the parent dropdown action for each child in the undo stack, we now search for the action related to the first parent cell selected for all the child dropdown actions.
1. Go to a test page that contains a Grid implemented with dropdown columns with dependency
2. Select multiple cells of the parent dropdown column
3. Press Delete
4. Press Ctrl+Z to undo
5. Check that …
> ROU-4439: Issue with dropdown column when deleting multiple cells

- src/Providers/DataGrid/Wijmo/Columns/DropdownColumn.ts
- src/Providers/DataGrid/Wijmo/Features/ValidationMark.ts
This PR is for fix the dropdown child triggering the OnCellValueChange more than once.
- When the Grid has a dropdown column with dependency, the OnCellValueChange event was triggered twice when the parent cell value changed.
- 
- Add validation to check if currentValue is different than empty when adding the child undo action and triggering the OnCellValueChange event.
- If the currentValue is already empty, we don't need to set the cell value to empty again and add it to the undo stack.
- Change the way we get the last parent cell's undo action on the undo stack.
- We want to ensure that the child's undo action is added to the last parent's undo action in the undo stack. 
- Disabled the trigger in the validateCell method to trigger the OnCellValueChange event just once.
- The …
> ROU-4519: Issue with dropdown column with dependency triggering OnCellValueChange event twice

- src/OSFramework/DataGrid/Enum/ErrorMessages.ts
- src/OSFramework/DataGrid/Feature/ExposedFeatures.ts
- src/OSFramework/DataGrid/Feature/ITooltip.ts
- src/OSFramework/DataGrid/Helper/GlobalEnum.ts
- src/Providers/DataGrid/Wijmo/Features/FeatureBuilder.ts
- src/Providers/DataGrid/Wijmo/Features/ToolTip.ts
- src/Providers/DataGrid/Wijmo/Helper/Constants.ts
This PR is to fix the issue with the custom tooltip when used in a Grid with Column Group
* When using the custom tooltip in a Grid with Column Group, the tooltip was not placed in the right column.
* The issue was that the column index returned by Wijmo cannot be used to get the column on the OSDG side when using a Grid with Column Group, because Wijmo does not consider the Column Group as it is done on OSDG side.
* Example: The "Price Tooltip" should have been placed in the Price column instead of the Stock column.
* Changed the Tooltip _setHeaderTooltip method to use the binding instead of the column index to get the column configs.
* Created a new file to place the constants used in the file
* Added a method to set the Column Group header tooltip
* Exposed the tooltip as a Data Grid …
> ROU-4571: Set custom tooltip on ColumnGroup

- src/Providers/DataGrid/Wijmo/Features/ValidationMark.ts
This PR is for fixing the dropdown with duplicated labels returning the wrong ID and not triggering OnCellValueChange
* When the Dropdown has duplicated labels with different values, the OnCellValueChange returns the wrong ID or is not triggered when changing to an option with the same label.
* Now, we store the previous cell value into the beginningEdit, to validate if the value was changed into cellEditEnded. 
1. Go to a page with a Grid containing dropdowns with duplicated option's labels
2. Change to another option with the same label
3. Check if the OnCellValue Changed was triggered and returns the correct value.
Before:
After:
> ROU-3712: Dropdown cell change handler returns wrong Id if text is duplicate

- src/Providers/DataGrid/Wijmo/Features/ColumnFilter.ts
- src/Providers/DataGrid/Wijmo/Helper/CellTemplateFactory.ts
This PR is for open SetColumnFilterOptions to work with more column types
* Add the capability to set column filter options to work with Number, Currency, Date and DateTime.
* Edited the setColumnFilterOptions method to consider Number, Currency, Date and DateTime column types.
* Edited the Error Message.
* Added toLowerCase() when checking if the "ExternalLink" options from the Action column is a binding or an external link.
> ROU-4659: Open SetColumnFilterOptions to work with more column types

- .vscode/settings.json
- src/OutSystems/GridAPI/Auxiliary.ts
- src/OutSystems/GridAPI/Pagination.ts
- src/OutSystems/GridAPI/Rows.ts
- src/OutSystems/GridAPI/Selection.ts
- src/OutSystems/GridAPI/View.ts
This PR contains a potential solution for how the APIs can start returning, in case of error, values more aligned with that.
The following APIs, were changed:
- `OutSystems.GridAPI.Rows.GetRowNumberByKey`
- `OutSystems.GridAPI.Pagination.GetCurrentPage`
> ROU-4651: solving incorrect outputs when API invokation fails

- src/Providers/DataGrid/Wijmo/Helper/CellTemplateFactory.ts
This PR will fix an issue at ActionColumn when LongInteger, Integer or Decimal type data was in use once the specification of comma delimitation was being not set properly.
Before the fix:
After the fix:
> ROU-4695: Fix an issue where the LongInteger, Integer and Decimal delimiter is no longer present at ActionColumn.

- src/OSFramework/DataGrid/Enum/ErrorMessages.ts
- src/Providers/DataGrid/Wijmo/Features/ColumnFilter.ts
This PR is to fix the filter popup not displaying the correct value when using FilterByCondition API in a Currency Column. It also corrects the issue of the filter not being applied to the correct column when the Grid has columns with the same binding.
* When using the FilterByCondition API to set a filter on a Currency column, the value passed to the _getFilterConditionValue was a string instead of a number.
* This prevented the condition value from appearing correctly in the filter popup. 
* When using the FilterByCondition API to set a filter to a column with duplicated binding in a Grid, the filter was always applied to the first column corresponding to the binding.
* In the ColumnFilter.byCondition method, added an evaluation was added to check if the target column is numerical. If …
> ROU-4691: Column Filter does not reflect the correct value when using FilterByCondition API

- src/OSFramework/DataGrid/Grid/AbstractDataSource.ts
This PR is for fix the GetChangedLines detecting changes when the Dropdown cell returns to its original value.
* In a Dropdown column, the Value attribute of the DropdownOptionList is always a Text by default. This way, even if the mapped values are of other data type, it will always be converted to Text.
* However, the Dropdown values of the data source are not automatically converted to Text.
* In the cases when the Dropdown Column values are of a different data type then Text, when changing a Dropdown value manually and then returning it to the original value, it will be replaced by a Text Value. This way a change is detected by the GetChangedLines.
* To fix this, we need to assure that the DropdownOptionList Values and the Dropdown Column values will always have the same data type. 
* …
> ROU-4765: GetChangedLines detect changes when Dropdown cell to the original value

- src/Providers/DataGrid/Wijmo/Features/ValidationMark.ts
This PR is for fixing the OnCellValueChange returning the dropdown label instead of the value when the SetCellData is called.
* When triggering the OnCellValueChange after calling the SEeCellData, it returned the dropdown's formatted value (label) instead of the option id/key. 
* In the Wijmo's getCellData method, we now set the last argument to false, this way we get the dropdown option id/key instead of the dropdown label.
* [] requires changes in OutSystems (if so, provide a module with changes)
> ROU-4768: Fix OnCellValueChange returning the dropdown label instead of the value

- src/Providers/DataGrid/Wijmo/Features/ValidationMark.ts
This PR is for fix MarkChangesAsSavedByKey not updating the cleaning invalid rows
* When using the MarkChangesAsSavedByKey Client Action with the ForceCleanInvalids parameter set to true and then calling the GetChangedLines, the HasInvalid property response was always true.
* This happened because we were not updating the invalidRows Set object when the MarkChangesAsSavedByKey is called.
* Added the _setRowStatusByKey method to the clearByRowKeys. This will update the rows invalidRows Set object.
> ROU-4829: Fix MarkChangesAsSavedByKey not updating the cleaning invalid rows

- src/Providers/DataGrid/Wijmo/Columns/DropdownColumn.ts
This PR is to fix the console error when opening a child dropdown without options
* In a Grid with two Dropdown columns dependent on each other, a console error occurs when the parent dropdown is erased and the child dropdown is opened.
* The error happened because nothing was returned in the getFilteredItems method when no option was selected in the parent dropdown. So Wijmo's code tried to access an undefined value.
* Fix the getFilteredItems to return an empty array when the parent dropdown value is empty.
Before:
After:
> ROU-4722: Fix console error when opening a child dropdown without options

- gulp/DefaultSpecs.js
This PR will update DefaultSpecs in order to remove a platform type that was used for testing proposes.
> Removed platform type

- src/OSFramework/DataGrid/Event/Feature/ContextMenuEventManager.ts
- src/OSFramework/DataGrid/Event/Feature/ContextMenuEventType.enum.ts
- src/OSFramework/DataGrid/Event/Feature/ContextMenuEvents.ts
- src/Providers/DataGrid/Wijmo/Features/ContextMenu.ts
This PR is for fixing the misbehavior of the ContextMenu, when options are added/removed/made disabled, on the on the event of the `OnMenuToggle` of the `ContextMenu` block.
* The changes made by the developer on a given column for the context menu:
* Adding a new Item
* Removing an item
* Making an item enabled
* Making an item disabled
* Evidence of the problem: 
* Made the event onToggle synchronous when the menu **is opening**
* This will allow the changes made by the developer on the callback to be reflected on the items
* This will cause the ChangeParameters to run before the method `_canRaiseClickEvent` is invoked
*  Made sure that when a context menu is opening, and an item is added or removed, that the itemSource is refreshed;
1. Open the test page
2. Right click on the column: …
> ROU-4904: Fix ContextMenu to allow item changes when clicking on a column

- src/Providers/DataGrid/Wijmo/Features/Export.ts
- styles/Grid.css
This PR will update the framework method `_showLoadingMessage` to stop using inline styles.
* In O11, when dealing with platform settings related to CSP and `unsafe-inline`, we identified an improvement we could make in the framework. 
* Added the following CSS utility classes
* Updated the framework method `_showLoadingMessage` to stop using inline styles and used the CSS utility classes mentioned above.
````
.full-size {
width: 100%;
height: 100%;
}
.ml-10 {
margin-left: 10px;
}
````
1. Go to a screen containing a Data Grid instance
2. On the dev tool’s console run → `OutSystems.GridAPI.GridManager.GetActiveGrid().features.export._showLoadingMessage()`
3. Check that the loading status continues to work as expected
> ROU-10900 Updated _showLoadingMessage to stop using inline styles

- src/OSFramework/DataGrid/Feature/Auxiliar/MenuItem.ts
- src/Providers/DataGrid/Wijmo/Features/ContextMenu.ts
This PR is for changing the way that the context menu item order is calculated when adding it. 
The current change makes the order set by the developer to be kept  in runtime in the IDE.
- When a new element was added to the context menu, the order in which it appeared in runtime, could differ from the order in made in the IDE
- Changed the way the order is calculated:
- Instead of being calculated and then sorting the array, the code will now insert the element immediately in the right position;
- Removed field order from the context menu item object;
1. Go to the [test page](https://outsystemsui-dev.outsystemsenterprise.com/OSDataGridAutomation_ROU10824/ContextMenu_Dynamic)
2. Right click on the column Price (in any cell)
3. The ContextMenu should appear containing the elements in the …
> ROU-10824: change the way context menu order is calculated

- src/Providers/DataGrid/Wijmo/Features/Styling.ts
This PR is to fix the additional spaces when adding a new class to cssClass and cssClassAll.
* Check if classList is not empty before splitting the string into an array. If empty, return a empty array.
> ROU-10774: Fix additional spaces when adding a new class to cssClass and cssClassAll

- src/Providers/DataGrid/Wijmo/Features/ValidationMark.ts
This PR is to remove the OnCellValueChange trigger from ApplyRowValidations API
- When using the ApplyRowValidations Client Action in a Grid with Dropdown Dependency, the child dropdown cell was being erased
- This happened because the ApplyRowValidations triggers the OnCellValueChange event of the Column and the Dropdown Column's _parentCellValueChangeHandler method was not considering this scenario.
* Removed the OnCellValueChange event trigger when calling the ApplyRowValidations. 
* This intruduces a breaking change.
1. Go to a page with a Grid with Dropdown Dependency
2. Run the ApplyRowValidations Client Action
3. Check that no cells were erased
4. Check that the OnCellValueChange was not triggered
> ROU-4896: Remove OnCellValueChange trigger from ApplyRowValidations API

- styles/Grid.css
* When using Dropdown Server Side, Dropdown Search, Dropdown Tags, and Date Pickers.
* Added a specific selector to override the style since the z-index is being handled inline by Wijmo Flexgrid
1. Open a screen with a Dropdown Server Side on top of a Grid
2. Open the Dropdown and check the ballon is now over all the Grid elements
3. Repeated the same steps for Dropdown Search, Dropdown Tags, and Date Picker
- Before: 
- After:
> ROU-10979: Fix visual issue when using frozen columns with dropdowns 

- src/OSFramework/DataGrid/Configuration/Grid/FlexGridConfig.ts
- src/OSFramework/DataGrid/Configuration/IConfigurationGrid.ts
- src/OutSystems/GridAPI/GridManager.ts
- src/Providers/DataGrid/Wijmo/Columns/ActionColumn.ts
- src/Providers/DataGrid/Wijmo/Columns/ImageColumn.ts
- src/Providers/DataGrid/Wijmo/Features/ContextMenu.ts
- src/Providers/DataGrid/Wijmo/Helper/CellTemplateFactory.ts
This PR is for adding the new `sanitizeInputValues` configuration.
* When passing HTML to the Grid, mainly on Action and Image Columns and the ContextMenu., we opened a door to an XSS vulnerability.
* Added a new `sanitizeInputValues` configuration to allow the developer to control when to sanitize the Grid's data.
* The default will be `sanitizeInputValues = true` so this will be a needed **breaking change**.
1. Open a screen with a Link Column 
2. On the Get From Other Sources add to the first position the following text `Test <img src=x onerror='alert(String.fromCharCode(88,83,83))'>`
3. Check that now we can see the text and no code is executed
- Before:
- After the fix:
> ROU-11001: Added sanitizeInputValues configuration

- src/OutSystems/GridAPI/ColumnManager.ts
This PR is to fix ConditionalFormat RowClass not being applied when there are two Grids in the screen.
* When using the `GetGridByColumnId` method was returning the wrong Grid object when there was two Grids in the DOM.
* Now, we obtain the Grid object through the Colum object instead.
> ROU-10980: The class that should have been set for the RowClass of TextColumn is not being applied

- gulp/DefaultSpecs.js
- package.json
- src/OSFramework/DataGrid/Constants.ts
- src/Providers/DataGrid/Wijmo/Features/ToolTip.ts
* There was an issue where the column headers displayed incorrect tooltip content when using grouped columns in a Grid:
* Improved the validation about the tooltip method to be called on the internal event handler `_onMouseEnter(e)` because if the _Column Header_ is from a _Group Column_, we need to use a different approach than the regular header.
* We can check if the current target is a _ColumnGroup_ by checking its CSS class `wj-colgroup` and, if there is no binding and the number of `columns` inside _ColumnGroup_ > 0 or if the number of `columnGroups` inside _ColumnGroup_ > 0.
1. Go to a screen with two Grids, one with Grouped Columns and another without
2. On the one with Grouped Columns hover all Column Headers and check that the tooltip content is the expected
3. Repeat the same …
> ROU-11327: Fix tooltip issue with Grouped Columns and increment version

- styles/Grid.css
This PR is for fixing the align of the content in the cells.
* The visual experience of editing DataGrid cells was undesirable.
* All DataGrid cells are now vertically aligned to the center, including when being edited.
> ROU-10908: Align DataGrid cells vertically to the center

- package.json
- src/OSFramework/DataGrid/Enum/ErrorCodes.ts
- src/OSFramework/DataGrid/Feature/IGroupPanel.ts
- src/OutSystems/GridAPI/ColumnManager.ts
- src/Providers/DataGrid/Wijmo/Features/GroupPanel.ts
This PR is for implementing a new `RemoveColumnsFromGroupPanel` API
* New feature ⭐
* Implemented new `RemoveColumnsFromGroupPanel` APIs
* Updated dev dependency for `@types/lodash`
1. Add columns to the group panel
2. Click on a button executing the client action `RemoveColumnsFromGroupPanel`
3. Check that the columns are removed
> ROU-11649: Implemented RemoveColumnsFromGroupPanel API

- styles/Grid.css
* After undoing (Ctrl/Cmd+Z) an undoable action like a cell value update or a column sort, a forceful scroll occurred, which could hide part of the UI above the DataGrid.
* The element with CSS class `datagrid-container` had its height set to 100%, which then caused the `osui-tabs__content-item` to have a higher scroll height than `BoundingClientRect.height`. 
* This behaviour caused a scroll to happen when an action was undone and the DataGrid was focused.
* This happened when not setting a fixed height for the Grid.
* The `datagrid-container` can be styled so that its height is set to `inherit` which should fix the issue and cause no harm for other use cases.
1. Add the Tabs component to a Screen
2. Add some elements like some Buttons to the beginning of the “Content” placeholder in one …
> ROU-11690: Incorrect scroll interaction of a Grid within Tabs

- .github/workflows/build.yaml
- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
This PR is for updating how the pre-release workflow is invoked.
> ROU-11492: Using GPG secret temporarely

- .github/workflows/build.yaml
- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
Adding event `synchronize` so that the PR related workflows, run every time the PR is open, reopen, or new commits added to it.
> ROU-11492: adding synchronize PR event 

- src/Providers/DataGrid/Wijmo/Features/ContextMenu.ts
This PR is for fix issue when a cell is copied using the Context Menu after being edited.
* When a cell was edited and then copied using the Context Menu, the change was not being tracked when running the Get Changed Lines.
* Now we set the focus to the active cell after finishing the Context Menu action.
* This is is similar what is implemented in [this Wijmo example](https://developer.mescius.com/wijmo/demos/Grid/ContextMenus/purejs).
* Despite in the example the Grid is refreshed, this was not suitable for other use cases. For example, when adding a new row via Context Menu, the dirty marks were not appearing because the Grid has been refreshed.
1. Go to a test page.
2. Edit a cell.
3. In the same cell, right click to open the Context Menu.
4. Click "Copy".
5. Run the Get Changed Lines …
> ROU-12064: Pasting into Grid cell followed by Right-Click copy marks cell as unedited

- src/Providers/DataGrid/Wijmo/Grid/FlexGrid.ts
This PR is for fixing an issue that caused the Grid to return dirty lines, when in reality there weren't.
* When the API  `MarkChangesAsSavedByKey` was used for a given line, and a subsequent change was made in the same line and then rollback (ctrl+z), the grid would return the information that there line was changed, even though it shouldn't. 
* With a workaround provided by Mescius, we are now clearing another `map` where the values are kept, fixing this way the issue.
1. Change value of cell with text "test 1" to "edit 1"
2. Hit the button "enter"
3. Click on button "Clear all changes"
4. Notice the "Edited Items" grid contains the line that was changed
5. Click on the button "Clear first change"
6. Notice the "Edited Items" grid is now empty
7. Change value of cell with text "test 3" …
> ROU-12056: Adding fix for when SavedByKey is used
