CODEOWNERS, README.md, code/src/WijmoProvider/Helper/Translation.ts, code/styles/Grid.css
This PR is composed by 2 small fixes and adding css code.
* Nothing especifically. Just small improvements.
* Improving translation error text
* Adding css to the event block (preview in SS only)
* Changing README file:
* Adding build badge
* Adding deployment badge
* Fixing location of the License file 
* Removed @rvalim from CODEOWNERS (not to be pulled automatically to every PR)
=> Small improvements

code/src/OSFramework/Grid/AbstractGrid.ts
* Whenever we used server-side search, the columns were being duplicated
* Added a condition before the step of adding columns
1. Open sample
2. On server-side search, search for pink
3. Check if new columns were not added. 
=> RGRIDT-770: Check if column exists before adding them again

code/package-lock.json, code/package.json
This PR is for updating the versions of lodash, typescript and wijmo modules.
This update doesn't have impact in runtime since we're adding the lodash, and wijmo files manually.
=> Update of the lodash version

code/src/WijmoProvider/Features/Export.ts
This PR fixes conditional format not being applied on excel export.
* Conditional format was not being applied on excel export.
* Adjusted exportToExcel method in order to apply conditional format on all cells
=> RGRIDT-832: Fixing export excel with styles

code/src/OSFramework/Grid/AbstractGrid.ts
* Whenever the user switched data sources, the grid wasn’t adding new rows and data.
* Created a new method that checks whether columns are new compared to existing ones and adds/removes them if necessary.
* Fixed eslint issues on AbstractGrid
=> RGRIDT-831: Changing Data Source with Drop Down

code/src/WijmoProvider/Features/ToolTip.ts
=> RGRIDT-877:  Fixing tooltip

code/src/WijmoProvider/Grid/FlexGrid.ts
This PR is for fixing the misbehavior of Safari 14.x in the paint when the scroll is done.
This is only a workaround until the safari issue is solved.
=> RGRIDT-893: Fixing the safari 14 related issue

code/src/GridAPI/Rows.ts, code/src/OSFramework/Configuration/Grid/FlexGridConfig.ts, code/src/OSFramework/Configuration/IConfigurationGrid.ts, code/src/OSFramework/Enum/OS_Config_Grid.ts, code/src/OSFramework/Event/Grid/GridEventType.enum.ts, code/src/OSFramework/Event/Grid/GridEventsManager.ts, code/src/OSFramework/Event/Grid/GridOnSortChangeEvent.ts, code/src/OSFramework/Feature/ExposedFeatures.ts, code/src/OSFramework/Feature/IRowNumber.ts, code/src/OSFramework/OSStructure/ActiveSorts.ts, code/src/WijmoProvider/Features/AutoRowNumber.ts, code/src/WijmoProvider/Features/ColumnFilter.ts, code/src/WijmoProvider/Features/ColumnSort.ts, code/src/WijmoProvider/Features/FeatureBuilder.ts, code/src/WijmoProvider/Grid/FlexGrid.ts, code/styles/Grid.css
This PR contains the changes necessary for server-side pagination.
* Create the ServerSidePagination input parameter
* Hide grid pagination when ServerSidePagination is true
* Show only Filter by Condition when ServerSidePagination is true
* Update API Activate filter to show only Filter by Condition when ServerSidePagination is true
* Create Client action to set the first value of grid auto numbering
* Create the OnSortChange event
=> RGRIDT-933: Server-side Pagination

code/src/GridAPI/Cells.ts
* On last PR, I had changed method name and forgot to update where it was being used.
* Updated method name on place it was being used.
=> RGRIDT-973: Forgot to change method name

code/src/OSFramework/Configuration/Column/EditorConfigDate.ts, code/src/WijmoProvider/Columns/AbstractProviderColumnEditor.ts, code/src/WijmoProvider/Columns/DateColumn.ts, code/src/WijmoProvider/Columns/DateTimeColumn.ts
This PR adds format to Date and DateTime columns.
=> RGRIDT-899: Adding format to date/dateTime columns

code/src/GridAPI/ContextMenu.ts, code/src/GridAPI/Rows.ts, code/src/OSFramework/Configuration/Grid/FlexGridConfig.ts, code/src/OSFramework/Configuration/IConfigurationGrid.ts, code/src/OSFramework/Feature/IValidationMark.ts, code/src/OSFramework/Grid/AbstractDataSource.ts, code/src/OSFramework/Grid/AbstractGrid.ts, code/src/OSFramework/Interface/IDataSource.ts, code/src/OSFramework/Interface/IRowMetadata.ts, code/src/WijmoProvider/Features/ValidationMark.ts, code/src/WijmoProvider/Grid/FlexGrid.ts, code/src/WijmoProvider/Grid/RowMetadata.ts
This PR delivers the necessary changes for server-side synchronization on grid.
* RGRIDT-934: Added new KeyBinding attribute.
* RGRIDT-967: Added new UpdateAddedLineKey API method.
* RGRIDT-968: Added new GetRowNumberByKey API method.
* RGRIDT-990: Added new SetValidationStatusByKey API method.
=> RGRIDT-934: Server side sync

code/src/GridAPI/ColumnManager.ts, code/src/OSFramework/Feature/IGroupPanel.ts, code/src/WijmoProvider/Features/GroupPanel.ts
This PR delivers the necessary changes to deliver SetColumnAggregate client action. This action will set the aggregate function on columns inside the group panel.
* Created SetColumnAggregate API method.
* Created new method on GroupPanel that sets aggregate into the function
1. Open Sample
2. Group description column
3. Price column should have the total sum on groups.
=> RGRIDT-908: SetColumnAggregate client action

code/src/OSFramework/Event/AbstractEvent.ts, code/src/OSFramework/Event/AbstractEventsManager.ts, code/src/OSFramework/Event/Column/AbstractColumnEvent.ts, code/src/OSFramework/Event/Column/ColumnEventsManager.ts, code/src/OSFramework/Event/Column/OnCellValueChange.ts, code/src/OSFramework/Event/Feature/ContextMenuEventManager.ts, code/src/OSFramework/Event/Feature/ContextMenuEvents.ts, code/src/OSFramework/Event/Grid/AbstractGridEvent.ts, code/src/OSFramework/Event/Grid/GridEventsManager.ts, code/src/OSFramework/Event/Grid/GridOnFiltersChangeEvent.ts, code/src/OSFramework/Event/Grid/GridOnSortChangeEvent.ts, code/src/OSFramework/Helper/AsyncInvocation.ts, code/src/WijmoProvider/Features/ValidationMark.ts, code/src/WijmoProvider/Grid/FlexGrid.ts
This PR is for improving the namings used in the events, and to make sure that they are run asynchronously. 
* There was a mismatch between the element type being stored in the EventManagers
* Some of the callbacks, were being executed synchronously.
* Changed the name of "handlers" to "events" - in the EventManagers
* Created a new helper action, that forces the execution of the code asynchronously using a setTimeout(..., 0)
1. The code should work as before.
=> Improving events

code/src/WijmoProvider/Features/ConditionalFormat.ts
This PR fixes a bug that happened when group panel was applied 
* There was a bug happening when group panel was applied.
* Added validation and refactored some of the code.
=> RGRIDT-1063: Refactoring and adding some extra validation

code/src/OSFramework/Helper/Sanitize.ts, code/src/WijmoProvider/Features/ToolTip.ts
* There was a [post ](https://www.outsystems.com/forums/discussion/74787/data-grid-reactive-is-datagrid-reactive-protected-against-xss/)on the forum that reported XSS vulnerability on tooltips.
* Created sanitize helper function.
* Sanitized tooltip values.
=> RGRIDT-1092: Sanitizing tooltip values

code/src/GridAPI/Sort.ts, code/src/OSFramework/Feature/IColumnSort.ts, code/src/WijmoProvider/Features/ColumnSort.ts
This PR adds the required methods for column sorting.
* Created API method for Column sorting and necessary methods for it to work.
=> RGRIDT-1066: Creating column sort api method

code/src/WijmoProvider/Features/ConditionalFormat.ts
This PR fixes a bug on text column group panel.
=> RGRIDT-1063: Bug fix text column group panel

code/src/WijmoProvider/Features/ColumnFilter.ts
This PR updates error message.
=> RGRIDT-1097: Updating error message

code/src/GridAPI/View.ts, code/src/OSFramework/Enum/ErrorCodes.ts, code/src/WijmoProvider/Features/View.ts, code/src/WijmoProvider/Grid/FlexGrid.ts
This PR adds feedback messages to View API methods. Both GetViewLayout and SetViewLayout methods did not return any feedback whether or not the operation was successful or if any errors happened. 
1. Press Load User A button
Expected: Error message should show saying: "It seems you are not passing a valid config."
1. Change grid columns
2. Press Save User A button
3. Success message saying "View saved successfully" should appear
4. Change grid columns again
5. Press Load User A button
Expected: Grid should change according to predefined configuration and success message should appear
=> ROU-3024: Adding return message to View API methods

code/src/GridAPI/Cells.ts, code/src/GridAPI/GridManager.ts, code/src/GridAPI/Rows.ts, code/src/OSFramework/Enum/ErrorCodes.ts, code/src/OSFramework/Enum/ErrorMessages.ts
This PR adds feedback messages to Data API and Validation methods. 
* Every method on this APIs did not return any feedback on whether or not the operation was successful or if any errors happened.
* Creation of 6 new ErrorCodes;
* Creation of 1 error message for column not found;
* Change GetChangesInGrid method;
* Change MarkChangesAsSaved method;
* Change SetCellData method;
* Change SetValidationStatus method;
* Change SetValidationStatusByKey method;
1. Change a cell, check cell mark
2. Click in "Get Changed Lines":
Expected: Row content that was changed should be shown in the page and a success message should appear.
3. Click in "Mark Changes as Saved":
Expected: Marks should be cleared and a success message should appear.
4. Click in "Get Changed Lines Invalid":
Expected:  Error …
=> ROU-3053: Data/Validation client actions should return error message and success boolean

code/src/GridAPI/ColumnFreeze.ts, code/src/GridAPI/ColumnManager.ts, code/src/OSFramework/Enum/ErrorCodes.ts, code/src/OSFramework/Enum/ErrorMessages.ts, code/src/WijmoProvider/Features/GroupPanel.ts
This PR is for adding error management for Columns.
* Added Error Codes for Columns
* Added try/catch on SetColumnAggregate, FreezeColumns, FreezeColumnsByActiveCell, HasFrozenColumns, UnfreezeColumns
* On Service Studio, created a structure representing the return message to each client action.
=> ROU 3048 - Column/ColumnFreeze client actions should return error message and success boolean

code/src/OSFramework/Enum/ErrorMessages.ts, code/src/WijmoProvider/Features/ColumnFreeze.ts
This PR adds missing error message on column freeze
=> ROU-3048: Adding error message

code/src/GridAPI/Rows.ts, code/src/OSFramework/Enum/ErrorCodes.ts, code/src/OSFramework/Enum/ErrorMessages.ts, code/src/OSFramework/Grid/AbstractDataSource.ts, code/src/WijmoProvider/Features/AutoRowNumber.ts, code/src/WijmoProvider/Features/Rows.ts
This PR is for the improvements on Row error messages on Grid. Please check the JIRA issue for more information.
=> ROU-3050: Row messages improvements

code/extension/DataGridDataConvert/Source/NET/temp_ardoJSON.cs
This PR fixes an issue where ArrangeData was returning wrong dates whenever we had Null Dates on a server that had a daylight saving.
*  Only convert date to UTC if the date is not null
=> ROU-3087: Fix null date issue

code/src/WijmoProvider/Features/Rows.ts
We accidentally removed a piece of code to the addClass method.
=> ROU-3050: Add missing code

code/src/OSFramework/Event/Column/ColumnEventsManager.ts, code/src/OSFramework/Event/Column/OnCellValueChange.ts
This PR is for remove OnCellValueChange async trigger and set it definitely sync.
Since we had an IF checking if the action that trigger the OnCellValueChange was performed by a Filter it was synchrony triggered and changing it to be definitely synchrony triggered it will solve the Issue when copy & paste a row that have child cells (Parent Binding)
=> ROU-3183: Fix Issue when copy & paste a row that have child cells

code/src/WijmoProvider/Columns/NumberColumn.ts, jobs/azure-pipelines-reactive.yml
This PR fixes an issue where decimal places weren't being properly set.
1. Select a random cell from Price
2. Type F2
3. Type 9999999999
4. Press Enter
Expected
- Cell value = 8,589,934,591
- Column Price present currency symbol"
=> ROU-3213: Fixing issue with decimal places

code/src/WijmoProvider/Features/ToolTip.ts
This PR is for add Tooltip to the ColumnFooter cells as we have for content cells as well when cell content doesn't fit!
=> ROU-3100: [Tooltip at ColumnFooter cells]

code/src/GridAPI/Styling.ts, code/src/OSFramework/Enum/ErrorCodes.ts, code/src/OSFramework/Feature/IStyling.ts, code/src/WijmoProvider/Features/Styling.ts
This PR is for an API that allows the developer to set the column with wordwrap.
* Create API SetColumnWordWrap;
1. Add the API to a flow;
2. Check if the column text changed;
=> ROU-2905: [DataGrid] - Column header/cells word wrap 

code/src/WijmoProvider/Features/GroupPanel.ts
This PR is for fixing a behavior using IDs on the new method, that was only working by binding.
=> ROU-3025 - v2

code/src/GridAPI/Rows.ts, code/src/OSFramework/Enum/ErrorMessages.ts, code/src/OSFramework/Feature/IRows.ts, code/src/WijmoProvider/Features/Rows.ts
This PR adds a new input parameter to the AddNewRows client action.
1.  Fill the input with the value 3
2. Click on button "Add NewRows"
Expected: 3 new rows will be added
#
1.  Fill the input with the value 0
2. Click on button "Add NewRows"
Expected: An error will be show and no rows will be added.
#
1.  Fill the input with the value 30
2. Click on button "Add NewRows"
Expected: An error will be show and no rows will be added.
=> ROU-3487: Adding numberOfRows param

code/src/GridAPI/ColumnManager.ts, code/src/OSFramework/Enum/ErrorCodes.ts, code/src/OSFramework/Feature/ExposedFeatures.ts, code/src/OSFramework/Feature/IColumn.ts, code/src/WijmoProvider/Features/Column.ts, code/src/WijmoProvider/Features/FeatureBuilder.ts
This PR adds SetColumnHeader client action
1. Click on the button "SetColumnHeader"
2. Then The header of the column "ChangedColumn" is equal to "Changed"
3. And Check if the FeedBack message is ```Code: 200 ErrorMessage: Success```
#
1. Click on the button "SetColumnHeader (wrong column)"
2. Then The header of the column "ChangedColumn" is equal to "Product Name"
3. And Check if the FeedBack error message is shown
#
1. Click on the button "SetColumnHeader"
2. Then The header of the column "ChangedColumn" is equal to "Changed"
=> ROU-2923: Adding SetColumnHeader client action

code/src/OSFramework/Feature/IGridReorder.ts, code/src/OSFramework/Helper/JSONParser.ts, code/src/WijmoProvider/Features/GridReorder.ts, code/src/WijmoProvider/Features/View.ts
This PR removes save/apply layout from row reorder due to possible breaking changes with local storage limit size.
=> ROU-3513: Removing save layout from row reorder

code/src/OSFramework/Grid/AbstractGrid.ts, code/src/OSFramework/Helper/AsyncInvocation.ts, code/src/WijmoProvider/Grid/FlexGrid.ts
This PR fixes a bug where we forgot to trigger Initialize on JSONSerialized events.
1. Both grids should have pagination filled correctly.
=> ROU-3538: Triggering Initilize on JsonSerialize Grids

code/src/OSFramework/Event/Grid/GridEventType.enum.ts, code/src/OSFramework/Event/Grid/GridEventsManager.ts, code/src/OSFramework/Event/Grid/OnColumnPickerChangeEvent.ts, code/src/OSFramework/Feature/IColumnPicker.ts, code/src/WijmoProvider/Features/ColumnPicker.ts
This PR adds the column picker event.
1. Hide Product Name on Grid with columns.
Expected: ColumnId and Column Binding should be filled and IsVisible should be false.
#
1. Hide Product Name on Grid with columns.
2. Show Product  Name Column on column picker .
Expected: ColumnId and Column Binding should be filled and IsVisible should be true.
#
1. Hide Name Column on column picker on Autogenerated Grid.
Expected: Column Binding should be filled and IsVisible should be false.
#
1. Hide Name Column on column picker on Autogenerated Grid.
3. Show Name  Column on column picker on Autogenerated Grid.
Expected: Column Binding should be filled and IsVisible should be true.
=> ROU-3558: Creating column picker event

code/src/OSFramework/Feature/IRows.ts, code/src/OutSystems/GridAPI/Rows.ts, code/src/WijmoProvider/Features/Rows.ts
This PR adds a new output parameter to AddRows client action.
1. Change NumberOfRows input to 5.
2. Press AddNewRows button
Expected: Text area should contain [0,1,2,3,4]
=> ROU-3612: Adding output parameter to addRows

package-lock.json, src/OSFramework/DataGrid/Enum/ErrorCodes.ts, src/OSFramework/DataGrid/Enum/ErrorMessages.ts, src/OSFramework/DataGrid/Feature/ISelection.ts, src/OutSystems/GridAPI/Selection.ts, src/Providers/DataGrid/Wijmo/Features/Selection.ts
This PR creates SetRowAsSelected client action.
1. Press SelectRows button
Expected: The rows with index [0, 2, 4] should be selected.
1. Press UnselectRows button
Expected: The rows with index [0, 2, 4] should be unselected.
=> ROU-3643: [SetRowAsSelected API method]

src/OSFramework/DataGrid/Feature/ExposedFeatures.ts, src/OSFramework/DataGrid/Feature/ISearch.ts, src/OutSystems/GridAPI/GridManager.Events.ts, src/OutSystems/GridAPI/Search.ts, src/Providers/DataGrid/Wijmo/Features/FeatureBuilder.ts, src/Providers/DataGrid/Wijmo/Features/Search.ts, styles/Grid.css
This PR is for addind the search feature to grid, using the wijmo feature available. Please check the JIRA issue for more information.
=> ROU-3540: Add search wijmo component to grid as an accelerator component

src/OSFramework/DataGrid/Feature/ISearch.ts, src/OutSystems/GridAPI/Filter.ts, src/OutSystems/GridAPI/Search.ts, src/Providers/DataGrid/Wijmo/Features/Pagination.ts, src/Providers/DataGrid/Wijmo/Features/Search.ts
This PR is for adding the new features on search grid that will highlight the result values and show a messages when the grid doesn't have results. Also fixed the issue related to JS error on pagination, that was introduced with search feature. Please check the JIRA issues for more information.
=> ROU-3739: Add no results and highlight results features and fix issue on JS pagination

src/Providers/DataGrid/Wijmo/Features/DirtyMark.ts
Changed isDirtyRow and isDirtyCell to include lodash's isEqualWith function, so we don't have to deal ourselves with deep equality.
* There was a bug where if a date cell has a date and then the cell was cleared, making it empty (undefined), if we changed it to back to the original value,  our function would break, because we can't do undefined.toString. We used to compare dates using the toString method.
* Changed the way isDirtyRow works. Instead of looping all values of the row and keeping track of a notDirtyCell counters, I switched the method to use Array.prototype.some(), which basically checks if any element in the array passes a test. Using this is more performative than looping through all row items, because, on the first truthy return, it immediately returns true, not going over …
=> ROU-3772: Refactoring dirtyMark functions

src/OutSystems/GridAPI/Rows.ts
This PR is for rename RemoveRows and RemoveSelectedRows API methods.
=> Renaming RemoveRows and RemoveSelectedRows API methods

package-lock.json, package.json, src/OSFramework/DataGrid/Constants.ts
This PR is for update OSFramework Gird Version.
=> Updated version.

src/Providers/DataGrid/Wijmo/Features/ColumnFilter.ts, src/Providers/DataGrid/Wijmo/Helper/FilterFactory.ts
This PR is for the filter type validation, when the column if from type Date or DateTime.
=> ROU-4109: fix filter condition validation

package-lock.json, package.json
This PR is for fixing the correct version before code-freeze.
=> Fix release version

package-lock.json, package.json, src/OSFramework/DataGrid/Constants.ts
This PR is to update the version to 2.11.0
=> Update version to 2.11.0

src/OSFramework/DataGrid/Enum/ErrorMessages.ts, src/OSFramework/DataGrid/Feature/ISelection.ts, src/OSFramework/DataGrid/Feature/IValidationMark.ts, src/OSFramework/DataGrid/Feature/IView.ts, src/OSFramework/DataGrid/Interface/ISerializable.ts, src/OSFramework/DataGrid/OSStructure/BindingValue.ts, src/OSFramework/DataGrid/OSStructure/RowData.ts, src/OSFramework/DataGrid/Types/index.ts, src/OutSystems/GridAPI/Cell.ts, src/OutSystems/GridAPI/ColumnPicker.ts, src/OutSystems/GridAPI/Export.ts, src/OutSystems/GridAPI/Pagination.ts, src/OutSystems/GridAPI/Rows.ts, src/OutSystems/GridAPI/Selection.ts, src/OutSystems/GridAPI/Styling.ts, src/OutSystems/GridAPI/View.ts, src/Providers/DataGrid/Wijmo/Features/Rows.ts, src/Providers/DataGrid/Wijmo/Features/Selection.ts, src/Providers/DataGrid/Wijmo/Features/ValidationMark.ts, src/Providers/DataGrid/Wijmo/Features/View.ts, src/Providers/DataGrid/Wijmo/Grid/FlexGrid.ts
This PR is for make error handling consistent on APIs
* Updated the API methods to use the CreateApiResponse function when necessary.
* Updated methods called in API methods to just return the value instead of a ReturnMessage.
* Removed any types
=> ROU-3808: Make error handling consistent on APIs

.vscode/settings.json, LICENSE, README.md, docs/README.md, package-lock.json, package.json
Added license BDS-3 to this repository.
=> Added license BDS-3 to this repository

package-lock.json, package.json, src/OSFramework/DataGrid/Constants.ts
This PR is to update the version to 2.13.1
=> Update version to 2.13.1

package-lock.json, package.json, src/OSFramework/DataGrid/Constants.ts
This PR is to update to version 2.15.0
* Updated to version 2.15.0
=> Update to version 2.15.0

README.md
This PR is for improving the readMe file with info for:
- How to sign up for the announcement list
- Keywords
This is parts of current internal requirements.
=> improve readMe

package-lock.json, package.json, src/OSFramework/DataGrid/Constants.ts
This PR is to update the version to 2.15.1
=> ROU-0 Update version to 2.15.1

gulp/DefaultSpecs.js, package.json, src/OSFramework/DataGrid/Constants.ts
This PR will update the development version.
=> ROU-10869: Update repo version.

gulp/DefaultSpecs.js, package.json, src/OSFramework/DataGrid/Constants.ts
This PR will increase dev version.
=> ROU-11399: Update dev version.

.github/os-git-actions/setup-gpg/action.yml, .github/os-git-actions/signed-commit/action.yml, .github/workflows/DevPR.yml, .github/workflows/PreRelease.yml
This PR is for adding small improvements on the github actions.
- The way the github actions were accessing to the secrets and passing as input parameter to other actions;
- The version of the external github action `actions/checkout`
- Now, github actions that require secrets access to them directly
- `actions/checkout` was standardized to v4
- Tested changes in the sandbox
-   [x] tested locally
-   [ ] documented the code
-   [ ] clean all warnings and errors of eslint
-   [ ] requires changes in OutSystems (if so, provide a module with changes)
-   [ ] requires new sample page in OutSystems (if so, provide a module with changes)
=> ROU-11456: Small improvements in pipelines

src/Providers/DataGrid/Wijmo/Features/Styling.ts, styles/Grid.css
This PR is for...
[Sample page](https://outsystemsui-dev.outsystemsenterprise.com/OutSystemsDataGridSample_ROU10908/Screen2?_ts=638727123084412660)
* The visual experience of editing DataGrid cells was undesirable.
* All DataGrid cells are now vertically aligned to the center, including when being edited.
1. 
=> ROU-10908: Align DataGrid cells vertically to the center

gulp/DefaultSpecs.js, package.json, src/OSFramework/DataGrid/Constants.ts
- This PR is to increment the dev version to 2.20.0
=> ROU-11574: Increment dev version to 2.20.0

.github/os-git-actions/setup-gpg/action.yml, .github/os-git-actions/signed-commit/action.yml, .github/workflows/PreRelease.yml, jobs/azure-pipelines-reactive.yml
* Update azure-pipelines.yml for Azure Pipelines
* Revert "Update azure-pipelines.yml for Azure Pipelines"
This reverts commit 025c9ab6d4dbf435966a6bbdc29d24d97140e02b.
* Update CODEOWNERS
* Merge release 2.9.0 (#281)
* ROU-3513: Changing ColumnReorder to GridReorder
* ROU-3513: Creating RowReorder api
* ROU-3513: Removing code smell
* ROU-3513: eslint
* ROU-3516: Adding column reorder event
* ROU-3520: Calculated column
Fixed issue where similar names didn't work properly
* ROU-3516: Adding private methods
* ROU-3076: Renaming namespace
* ROU-3513: Removing save layout from row reorder
* ROU-3513: Removing JSON methods
* ROU-3076: moving readme
* Update GetClosestGrid.ts
* Update IsGridReady.ts
* ROU-3076: updating dateformat
* ROU-3076: Fixing code smell
* ROU-3528: Updating rows API …
=> ROU-11492: Fix access to secrets & Update based on main to fix merge conflicts
